-- AlterEnum: ActivityType에 AI 파이프라인 이벤트 타입 추가
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'AI_TASK_CREATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'AI_TASK_OPENED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'QUOTE_DRAFT_GENERATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'QUOTE_DRAFT_REVIEWED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'EMAIL_DRAFT_GENERATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'EMAIL_SENT';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'VENDOR_REPLY_LOGGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ORDER_FOLLOWUP_GENERATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ORDER_STATUS_CHANGE_PROPOSED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ORDER_STATUS_CHANGE_APPROVED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'INVENTORY_RESTOCK_SUGGESTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'INVENTORY_RESTOCK_REVIEWED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'PURCHASE_REQUEST_CREATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'AI_TASK_COMPLETED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'AI_TASK_FAILED';

-- AlterTable: ActivityLog에 AI 파이프라인 컬럼 추가
ALTER TABLE "ActivityLog" ADD COLUMN IF NOT EXISTS "taskType" TEXT;
ALTER TABLE "ActivityLog" ADD COLUMN IF NOT EXISTS "beforeStatus" TEXT;
ALTER TABLE "ActivityLog" ADD COLUMN IF NOT EXISTS "afterStatus" TEXT;
ALTER TABLE "ActivityLog" ADD COLUMN IF NOT EXISTS "actorRole" TEXT;

-- CreateIndex: 복합 인덱스 추가
CREATE INDEX IF NOT EXISTS "ActivityLog_entityType_entityId_idx" ON "ActivityLog"("entityType", "entityId");
CREATE INDEX IF NOT EXISTS "ActivityLog_taskType_idx" ON "ActivityLog"("taskType");
