/**
 * Actual Send Execution Workspace v2 — final irreversible execution control surface
 *
 * 고정 규칙: execution ready ≠ sent ≠ dispatched. center/rail/dock 분리.
 * Batch 1: execute_actual_send / mark_sent / mark_dispatched 금지.
 */

import type { ActualSendExecutionGateV2, FinalExecGateStatus, ActualSendExecutionCandidateV2 } from "./actual-send-execution-gate-v2-engine";
import type { DispatchPreparationHandoffPackageV2, InternalOnlyExcludedFlag } from "./dispatch-preparation-handoff-gate-v2-engine";

export type FinalExecWorkspaceStatus = "locked_preview_only" | "entry_enabled" | "execution_review_required" | "execution_review_in_progress" | "execution_hold" | "execution_review_pending" | "execution_ready_pending_run";
export type FinalExecWorkspaceMode = "preview_only" | "execution_review" | "irreversible_execution_check" | "policy_review" | "ready_pending_run";
export type FinalExecSectionKey = "recipient_execution_final_block" | "payload_integrity_execution_final_block" | "reference_instruction_execution_final_block" | "exclusion_guard_execution_final_block" | "actor_authorization_audit_execution_final_block" | "execution_completion_gate_review";
export type FinalExecSectionStatus = "ready" | "partial" | "warning" | "blocked" | "attention_required" | "reviewed";

export interface ActualSendExecutionCheckSectionStateV2 { sectionKey: FinalExecSectionKey; sectionTitle: string; sectionStatus: FinalExecSectionStatus; priorityRank: number; executionIntent: string; whyThisMatters: string; requiredExecutionInputs: string[]; resolvedInputs: string[]; unresolvedOrAmbiguousInputs: string[]; warnings: string[]; operatorActionRequired: string; canResolveInPlace: boolean; requiresReturnToActualSendCommitReview: boolean; requiresReturnToTransactionOrActionIfAny: boolean; nextBestActionLabel: string; payloadIntegrityBasis: string; exclusionGuardBasis: string; actorAuthorizationBasis: string; auditChainBasis: string; irreversibleExecutionBasis: string; }

export interface FinalExecFieldGroup { groupKey: string; groupLabel: string; sourceMapping: string; resolved: boolean; value: string; unresolved: boolean; excluded: boolean; }
export interface ActualSendExecutionCenterCanvasStateV2 { activeSectionKey: FinalExecSectionKey | null; decisionQuestion: string; executionContext: string; sourceInputSummary: string; unresolvedOrConflictingInputs: string[]; fieldGroups: FinalExecFieldGroup[]; riskSummary: string; resolutionOptions: string[]; blockedDownstreamActions: string[]; completionRuleForSection: string; }

export type FinalExecPreviewMode = "locked_preview" | "execution_candidate_preview" | "warning_preview" | "review_preview";
export interface ActualSendExecutionRightRailPreviewStateV2 { previewMode: FinalExecPreviewMode; recipientPreview: { vendorId: string; contactVisible: boolean }; payloadIntegrityPreview: { lineCount: number; amountSummary: string; scopeIntact: boolean }; referenceInstructionPreview: { quoteVisible: boolean; poVisible: boolean; shipToVisible: boolean; receivingVisible: boolean }; excludedInternalOnlyPreview: InternalOnlyExcludedFlag[]; actorAuthorizationAuditPreview: { actorTraceComplete: boolean; authorizationConfirmed: boolean; auditChainIntact: boolean }; previewCautionSummary: string; provenancePreview: { candidateId: string; lane: string }[]; }

export interface ActualSendExecutionStickyDockStateV2 { primaryAction: { label: string; enabled: boolean; reason: string }; secondaryActions: { label: string; enabled: boolean; reason: string }[]; disabledActions: { label: string; reason: string }[]; blockedActionReasons: Record<string, string>; requiredResolutionBeforeProgress: string | null; workspaceCompletionLabel: string; actualSendRunLockLabel: string; }

export interface ActualSendExecutionWorkspaceHeaderV2 { title: string; statusChip: string; entryStatusLabel: string; entryStatusReason: string; executionScopeLabel: string; currentGateLabel: string; nextGateLabel: string; operatorMandate: string; lockInterpretation: string; actualSendRunLockReason: string; }

export interface ActualSendExecutionWorkspaceStateV2 {
  workspaceId: string; caseId: string; handoffPackageId: string; actualSendCommitSessionId: string; actualSendExecutionGateId: string;
  workspaceStatus: FinalExecWorkspaceStatus; workspaceMode: FinalExecWorkspaceMode;
  workspaceHeader: ActualSendExecutionWorkspaceHeaderV2; entryLockSummary: string;
  checkSectionStates: ActualSendExecutionCheckSectionStateV2[]; activeSectionKey: FinalExecSectionKey | null;
  centerCanvasState: ActualSendExecutionCenterCanvasStateV2; rightRailPreview: ActualSendExecutionRightRailPreviewStateV2; stickyDock: ActualSendExecutionStickyDockStateV2;
  operatorFocusOrder: FinalExecSectionKey[]; provenance: { candidateId: string; lane: string }[]; generatedAt: string;
}

const META: Record<FinalExecSectionKey, { title: string; intent: string; risk: string; question: string }> = {
  recipient_execution_final_block: { title: "수신자 Execution 최종 확인", intent: "Irreversible execution 직전 수신자 확정", risk: "되돌릴 수 없는 오발송", question: "수신자가 irreversible execution에 모호함 없이 확정되었습니까?" },
  payload_integrity_execution_final_block: { title: "Payload Integrity Execution 최종 확인", intent: "최종 payload 정합성 확인", risk: "되돌릴 수 없는 주문 착오", question: "Payload가 최종 commit basis와 정합적입니까?" },
  reference_instruction_execution_final_block: { title: "Reference / Instruction Execution 최종 확인", intent: "Reference/instruction 최종 정합성", risk: "배송/입고 착오", question: "Reference와 instruction이 최종 basis와 정합적입니까?" },
  exclusion_guard_execution_final_block: { title: "Exclusion Guard Execution 최종 확인", intent: "Internal-only 최종 제외 확인", risk: "기밀 유출 — 되돌릴 수 없음", question: "Internal-only 문맥이 execution candidate에서 완전 제외되었습니까?" },
  actor_authorization_audit_execution_final_block: { title: "Actor / Authorization / Audit Execution 최종 확인", intent: "Execution actor authorization + audit chain 확인", risk: "Actor trace / audit chain gap 시 사후 추적 불가", question: "Actor authorization과 audit chain이 irreversible execution에 충분합니까?" },
  execution_completion_gate_review: { title: "Execution 완결성 확인", intent: "모든 execution block 완결 최종 검토", risk: "미확인 상태에서 run 시 복구 불가", question: "모든 execution block이 완결되어 run 준비가 되었습니까?" },
};

function buildFinalExecSection(key: FinalExecSectionKey, rank: number, pkg: DispatchPreparationHandoffPackageV2, resolved: string[], unresolved: string[], warnings: string[]): ActualSendExecutionCheckSectionStateV2 {
  const m = META[key]; const status: FinalExecSectionStatus = unresolved.length > 0 ? "blocked" : warnings.length > 0 ? "warning" : "ready";
  return { sectionKey: key, sectionTitle: m.title, sectionStatus: status, priorityRank: rank, executionIntent: m.intent, whyThisMatters: m.risk, requiredExecutionInputs: [...resolved, ...unresolved], resolvedInputs: resolved, unresolvedOrAmbiguousInputs: unresolved, warnings, operatorActionRequired: unresolved.length > 0 ? `${m.title} 해소 필요` : warnings.length > 0 ? `${m.title} 검토` : `${m.title} 확인 가능`, canResolveInPlace: unresolved.length === 0, requiresReturnToActualSendCommitReview: unresolved.length > 0, requiresReturnToTransactionOrActionIfAny: false, nextBestActionLabel: unresolved.length > 0 ? `${m.title} 해소` : `${m.title} 확인`, payloadIntegrityBasis: key === "payload_integrity_execution_final_block" ? "direct" : "inherited", exclusionGuardBasis: key === "exclusion_guard_execution_final_block" ? "direct" : "inherited", actorAuthorizationBasis: key === "actor_authorization_audit_execution_final_block" ? "direct" : "inherited", auditChainBasis: key === "actor_authorization_audit_execution_final_block" ? "direct" : "inherited", irreversibleExecutionBasis: "execution_review" };
}

function deriveSections(pkg: DispatchPreparationHandoffPackageV2): ActualSendExecutionCheckSectionStateV2[] {
  const s: ActualSendExecutionCheckSectionStateV2[] = [];
  const rR: string[] = []; const rU: string[] = []; if (pkg.createdVendorId) rR.push("vendorId"); else rU.push("vendorId"); if (pkg.vendorContactReferenceVisible) rR.push("contact"); else rU.push("contact");
  s.push(buildFinalExecSection("recipient_execution_final_block", 1, pkg, rR, rU, []));
  const pR: string[] = []; const pU: string[] = []; const pW: string[] = []; if (pkg.createdLineItems.length > 0) pR.push("lineItems"); else pU.push("lineItems"); if (pkg.createdAmountSummary) pR.push("amount"); else pW.push("amount 누락"); if (pkg.dispatchEligibleScope) pR.push("scope"); else pU.push("scope");
  s.push(buildFinalExecSection("payload_integrity_execution_final_block", 2, pkg, pR, pU, pW));
  const refR: string[] = []; const refU: string[] = []; const refW: string[] = []; if (pkg.quoteReferenceVisible) refR.push("quote"); else refW.push("quote 비활성"); if (pkg.poReferenceVisible) refR.push("PO"); else refW.push("PO 비활성"); if (pkg.shipToVisible) refR.push("ship-to"); else refU.push("ship-to"); if (pkg.receivingInstructionVisible) refR.push("receiving"); else refW.push("receiving 비활성");
  s.push(buildFinalExecSection("reference_instruction_execution_final_block", 3, pkg, refR, refU, refW));
  const eR: string[] = []; const eU: string[] = []; const eW: string[] = []; if (pkg.internalOnlyExcludedFlags.length > 0) eR.push(`${pkg.internalOnlyExcludedFlags.length}건 제외`); const seedLower = (pkg.supplierFacingNoteSeed || "").toLowerCase(); if (["budget", "governance", "internal", "approval"].some(kw => seedLower.includes(kw))) eU.push("contamination risk"); if (pkg.internalOnlyExcludedFlags.length === 0 && pkg.supplierFacingNoteSeed) eW.push("exclusion flag 없이 note seed 존재");
  s.push(buildFinalExecSection("exclusion_guard_execution_final_block", 4, pkg, eR, eU, eW));
  const aR = ["actor_trace", "authorization", "audit_chain"]; const aW: string[] = []; if (pkg.provenanceByLine.length === 0) aW.push("provenance 누락");
  s.push(buildFinalExecSection("actor_authorization_audit_execution_final_block", 5, pkg, aR, [], aW));
  const blocked = s.filter(x => x.sectionStatus === "blocked"); const warned = s.filter(x => x.sectionStatus === "warning");
  s.push(buildFinalExecSection("execution_completion_gate_review", 6, pkg, s.filter(x => x.sectionStatus === "ready" || x.sectionStatus === "reviewed").map(x => x.sectionKey), blocked.map(x => `${x.sectionTitle} blocked`), warned.map(x => `${x.sectionTitle} warning`)));
  return s;
}

function deriveStatus(gate: ActualSendExecutionGateV2, secs: ActualSendExecutionCheckSectionStateV2[]): FinalExecWorkspaceStatus {
  if (gate.gateStatus !== "eligible_for_actual_send_execution" && gate.gateStatus !== "actual_send_execution_opened") return "locked_preview_only";
  const hasB = secs.some(x => x.sectionStatus === "blocked"); const hasW = secs.some(x => x.sectionStatus === "warning" || x.sectionStatus === "attention_required"); const allDone = secs.every(x => x.sectionStatus === "ready" || x.sectionStatus === "reviewed");
  if (allDone) return "execution_ready_pending_run"; if (hasB) return "execution_review_required"; if (hasW) return "execution_review_in_progress"; return "entry_enabled";
}
function deriveMode(s: FinalExecWorkspaceStatus): FinalExecWorkspaceMode { switch (s) { case "locked_preview_only": return "preview_only"; case "entry_enabled": case "execution_review_required": return "execution_review"; case "execution_review_in_progress": return "irreversible_execution_check"; case "execution_hold": return "policy_review"; case "execution_review_pending": return "execution_review"; case "execution_ready_pending_run": return "ready_pending_run"; } }

const FOCUS: FinalExecSectionKey[] = ["recipient_execution_final_block", "payload_integrity_execution_final_block", "reference_instruction_execution_final_block", "exclusion_guard_execution_final_block", "actor_authorization_audit_execution_final_block", "execution_completion_gate_review"];
function deriveFocus(secs: ActualSendExecutionCheckSectionStateV2[]): FinalExecSectionKey[] { const b = FOCUS.filter(k => secs.find(x => x.sectionKey === k)?.sectionStatus === "blocked"); const w = FOCUS.filter(k => { const x = secs.find(s => s.sectionKey === k); return x && (x.sectionStatus === "warning" || x.sectionStatus === "attention_required") && !b.includes(k); }); const r = FOCUS.filter(k => !b.includes(k) && !w.includes(k)); return [...b, ...w, ...r]; }

export function buildActualSendExecutionWorkspaceStateV2(gate: ActualSendExecutionGateV2, pkg: DispatchPreparationHandoffPackageV2): ActualSendExecutionWorkspaceStateV2 {
  const secs = deriveSections(pkg); const status = deriveStatus(gate, secs); const mode = deriveMode(status); const focus = deriveFocus(secs);
  const isLocked = status === "locked_preview_only"; const isReady = status === "execution_ready_pending_run"; const hasB = secs.some(x => x.sectionStatus === "blocked");
  const header: ActualSendExecutionWorkspaceHeaderV2 = { title: `Actual Send Execution — ${gate.caseId}`, statusChip: isLocked ? "Preview Only" : isReady ? "Execution Ready — Run 대기" : hasB ? "차단됨" : "Execution 검토 가능", entryStatusLabel: isLocked ? "Entry Locked" : "Entry Enabled", entryStatusReason: isLocked ? gate.candidate.candidateReason : "Execution 가능", executionScopeLabel: gate.candidate.payloadIntegrityFinalSnapshot, currentGateLabel: "Actual Send Execution Control", nextGateLabel: "Actual Send Run Action (Locked — Batch 1)", operatorMandate: isLocked ? "Preview only." : hasB ? "Execution 미확인 항목 해소 필요" : isReady ? "Execution ready — run 활성화를 기다리세요." : "Execution 직전 각 항목 확인", lockInterpretation: isReady ? "Execution ready — run은 아직 범위 밖" : isLocked ? "Gate 조건 미충족" : "Execution 검토 가능", actualSendRunLockReason: "Batch 1: Actual send run, sent, dispatched 처리는 현재 범위 밖입니다" };
  const dock: ActualSendExecutionStickyDockStateV2 = { primaryAction: isLocked ? { label: "Preview Only", enabled: false, reason: "Entry locked" } : isReady ? { label: "Execution Ready — Run 대기", enabled: false, reason: "Run 활성화 대기" } : hasB ? { label: "미확인 해소", enabled: true, reason: "" } : { label: "Execution 검토 계속", enabled: true, reason: "" }, secondaryActions: [{ label: "Commit Review로 복귀", enabled: true, reason: "" }, { label: "Hold 전환", enabled: true, reason: "" }, { label: "Section 확인 완료", enabled: !isLocked && !hasB, reason: hasB ? "Blocker 해소 필요" : "" }], disabledActions: [{ label: "Actual Send Run", reason: "Batch 1 범위 밖" }, { label: "Mark Sent", reason: "Batch 1 범위 밖" }, { label: "Mark Dispatched", reason: "Batch 1 범위 밖" }, { label: "Delivery Tracking", reason: "Batch 1 범위 밖" }], blockedActionReasons: { execute_actual_send_execution: "Batch 1 금지", mark_sent: "Batch 1 금지", mark_dispatched: "Batch 1 금지", create_delivery_tracking: "Batch 1 금지" }, requiredResolutionBeforeProgress: hasB ? secs.find(x => x.sectionStatus === "blocked")?.sectionTitle ?? null : null, workspaceCompletionLabel: isReady ? "Execution ready — run 대기" : "Execution 검토 진행 중", actualSendRunLockLabel: "Actual Send Run — Batch 1 locked" };
  const previewMode: FinalExecPreviewMode = isLocked ? "locked_preview" : isReady ? "execution_candidate_preview" : "review_preview";
  const cautions: string[] = []; if (!pkg.vendorContactReferenceVisible) cautions.push("Vendor contact 비활성"); if (!pkg.quoteReferenceVisible && !pkg.poReferenceVisible) cautions.push("Quote/PO 비활성"); if (pkg.internalOnlyExcludedFlags.length > 0) cautions.push(`${pkg.internalOnlyExcludedFlags.length}건 internal-only 제외`);
  const rail: ActualSendExecutionRightRailPreviewStateV2 = { previewMode, recipientPreview: { vendorId: pkg.createdVendorId, contactVisible: pkg.vendorContactReferenceVisible }, payloadIntegrityPreview: { lineCount: pkg.createdLineItems.length, amountSummary: pkg.createdAmountSummary, scopeIntact: !!pkg.dispatchEligibleScope }, referenceInstructionPreview: { quoteVisible: pkg.quoteReferenceVisible, poVisible: pkg.poReferenceVisible, shipToVisible: pkg.shipToVisible, receivingVisible: pkg.receivingInstructionVisible }, excludedInternalOnlyPreview: pkg.internalOnlyExcludedFlags, actorAuthorizationAuditPreview: { actorTraceComplete: pkg.provenanceByLine.length > 0, authorizationConfirmed: true, auditChainIntact: true }, previewCautionSummary: cautions.length > 0 ? cautions.join("; ") : "이슈 없음", provenancePreview: pkg.provenanceByLine.map(p => ({ candidateId: p.candidateId, lane: p.originalLane })) };
  const ak = focus[0] || null; const active = ak ? secs.find(x => x.sectionKey === ak) : null;
  const center: ActualSendExecutionCenterCanvasStateV2 = active ? { activeSectionKey: ak, decisionQuestion: META[ak!].question, executionContext: active.executionIntent, sourceInputSummary: `${active.resolvedInputs.length} resolved / ${active.unresolvedOrAmbiguousInputs.length} unresolved`, unresolvedOrConflictingInputs: [...active.unresolvedOrAmbiguousInputs, ...active.warnings], fieldGroups: active.requiredExecutionInputs.map(i => ({ groupKey: i, groupLabel: i, sourceMapping: "execution", resolved: active.resolvedInputs.includes(i), value: active.resolvedInputs.includes(i) ? "resolved" : "", unresolved: active.unresolvedOrAmbiguousInputs.includes(i), excluded: false })), riskSummary: META[ak!].risk, resolutionOptions: active.canResolveInPlace ? ["현재 workspace에서 확인 가능"] : ["Commit review로 복귀 필요"], blockedDownstreamActions: ["execute_actual_send_execution", "mark_sent", "mark_dispatched"], completionRuleForSection: active.unresolvedOrAmbiguousInputs.length > 0 ? "미확인 해소 후 reviewed 가능" : "즉시 reviewed 가능" } : { activeSectionKey: null, decisionQuestion: "", executionContext: "", sourceInputSummary: "", unresolvedOrConflictingInputs: [], fieldGroups: [], riskSummary: "", resolutionOptions: [], blockedDownstreamActions: ["execute_actual_send_execution", "mark_sent", "mark_dispatched"], completionRuleForSection: "" };

  return { workspaceId: `fnlexws_${Date.now().toString(36)}`, caseId: gate.caseId, handoffPackageId: gate.handoffPackageId, actualSendCommitSessionId: gate.actualSendCommitSessionId, actualSendExecutionGateId: gate.actualSendExecutionGateId, workspaceStatus: status, workspaceMode: mode, workspaceHeader: header, entryLockSummary: isLocked ? `Entry locked: ${gate.candidate.candidateReason}` : "Entry enabled", checkSectionStates: secs, activeSectionKey: ak, centerCanvasState: center, rightRailPreview: rail, stickyDock: dock, operatorFocusOrder: focus, provenance: pkg.provenanceByLine.map(p => ({ candidateId: p.candidateId, lane: p.originalLane })), generatedAt: new Date().toISOString() };
}

export type FinalExecWorkspaceEventType = "actual_send_execution_workspace_state_computed" | "actual_send_execution_workspace_opened_preview_only" | "actual_send_execution_workspace_entry_enabled" | "actual_send_execution_workspace_section_focused" | "actual_send_execution_workspace_section_review_started" | "actual_send_execution_workspace_marked_in_progress" | "actual_send_execution_workspace_marked_ready_pending_run";
export interface FinalExecWorkspaceEvent { type: FinalExecWorkspaceEventType; caseId: string; handoffPackageId: string; actualSendCommitSessionId: string; actualSendExecutionGateId: string; workspaceId: string; sectionKeyIfAny: FinalExecSectionKey | null; reason: string; actorOrSystem: string; timestamp: string; }
export function createFinalExecWorkspaceEvent(type: FinalExecWorkspaceEventType, ws: ActualSendExecutionWorkspaceStateV2, sectionKey: FinalExecSectionKey | null, reason: string, actor: string): FinalExecWorkspaceEvent { return { type, caseId: ws.caseId, handoffPackageId: ws.handoffPackageId, actualSendCommitSessionId: ws.actualSendCommitSessionId, actualSendExecutionGateId: ws.actualSendExecutionGateId, workspaceId: ws.workspaceId, sectionKeyIfAny: sectionKey, reason, actorOrSystem: actor, timestamp: new Date().toISOString() }; }
