/**
 * Actual Send Execute Workspace v2 — absolute terminal execute control surface
 *
 * 고정 규칙: execute ready ≠ sent ≠ dispatched. center/rail/dock 분리.
 * Batch 1: fire/mark_sent/mark_dispatched 금지.
 */

import type { ActualSendExecuteGateV2, ExecuteGateStatus, ActualSendExecuteCandidateV2 } from "./actual-send-execute-gate-v2-engine";
import type { DispatchPreparationHandoffPackageV2, InternalOnlyExcludedFlag } from "./dispatch-preparation-handoff-gate-v2-engine";

export type ExecuteWorkspaceStatus = "locked_preview_only" | "entry_enabled" | "execute_review_required" | "execute_review_in_progress" | "execute_hold" | "execute_review_pending" | "execute_ready_pending_fire";
export type ExecuteWorkspaceMode = "preview_only" | "execute_review" | "irreversible_execute_check" | "policy_review" | "ready_pending_fire";
export type ExecuteSectionKey = "recipient_execute_final_block" | "payload_integrity_execute_final_block" | "reference_instruction_execute_final_block" | "exclusion_guard_execute_final_block" | "actor_authorization_audit_execute_final_block" | "execute_completion_gate_review";
export type ExecuteSectionStatus = "ready" | "partial" | "warning" | "blocked" | "attention_required" | "reviewed";

export interface ActualSendExecuteCheckSectionStateV2 { sectionKey: ExecuteSectionKey; sectionTitle: string; sectionStatus: ExecuteSectionStatus; priorityRank: number; executeIntent: string; whyThisMatters: string; requiredExecuteInputs: string[]; resolvedInputs: string[]; unresolvedOrAmbiguousInputs: string[]; warnings: string[]; operatorActionRequired: string; canResolveInPlace: boolean; requiresReturnToActualSendRunReview: boolean; requiresReturnToExecutionOrCommitIfAny: boolean; nextBestActionLabel: string; payloadIntegrityBasis: string; exclusionGuardBasis: string; actorAuthorizationBasis: string; auditChainBasis: string; irreversibleExecuteBasis: string; }

export interface ExecuteFieldGroup { groupKey: string; groupLabel: string; sourceMapping: string; resolved: boolean; value: string; unresolved: boolean; excluded: boolean; }
export interface ActualSendExecuteCenterCanvasStateV2 { activeSectionKey: ExecuteSectionKey | null; decisionQuestion: string; executeContext: string; sourceInputSummary: string; unresolvedOrConflictingInputs: string[]; fieldGroups: ExecuteFieldGroup[]; riskSummary: string; resolutionOptions: string[]; blockedDownstreamActions: string[]; completionRuleForSection: string; }

export type ExecutePreviewMode = "locked_preview" | "execute_candidate_preview" | "warning_preview" | "review_preview";
export interface ActualSendExecuteRightRailPreviewStateV2 { previewMode: ExecutePreviewMode; recipientPreview: { vendorId: string; contactVisible: boolean }; payloadIntegrityPreview: { lineCount: number; amountSummary: string; scopeIntact: boolean }; referenceInstructionPreview: { quoteVisible: boolean; poVisible: boolean; shipToVisible: boolean; receivingVisible: boolean }; excludedInternalOnlyPreview: InternalOnlyExcludedFlag[]; actorAuthorizationAuditPreview: { actorTraceComplete: boolean; authorizationConfirmed: boolean; auditChainIntact: boolean }; previewCautionSummary: string; provenancePreview: { candidateId: string; lane: string }[]; }

export interface ActualSendExecuteStickyDockStateV2 { primaryAction: { label: string; enabled: boolean; reason: string }; secondaryActions: { label: string; enabled: boolean; reason: string }[]; disabledActions: { label: string; reason: string }[]; blockedActionReasons: Record<string, string>; requiredResolutionBeforeProgress: string | null; workspaceCompletionLabel: string; actualSendFireLockLabel: string; }

export interface ActualSendExecuteWorkspaceHeaderV2 { title: string; statusChip: string; entryStatusLabel: string; entryStatusReason: string; executeScopeLabel: string; currentGateLabel: string; nextGateLabel: string; operatorMandate: string; lockInterpretation: string; actualSendFireLockReason: string; }

export interface ActualSendExecuteWorkspaceStateV2 {
  workspaceId: string; caseId: string; handoffPackageId: string; actualSendRunSessionId: string; actualSendExecuteGateId: string;
  workspaceStatus: ExecuteWorkspaceStatus; workspaceMode: ExecuteWorkspaceMode;
  workspaceHeader: ActualSendExecuteWorkspaceHeaderV2; entryLockSummary: string;
  checkSectionStates: ActualSendExecuteCheckSectionStateV2[]; activeSectionKey: ExecuteSectionKey | null;
  centerCanvasState: ActualSendExecuteCenterCanvasStateV2; rightRailPreview: ActualSendExecuteRightRailPreviewStateV2; stickyDock: ActualSendExecuteStickyDockStateV2;
  operatorFocusOrder: ExecuteSectionKey[]; provenance: { candidateId: string; lane: string }[]; generatedAt: string;
}

const META: Record<ExecuteSectionKey, { title: string; intent: string; risk: string; question: string }> = {
  recipient_execute_final_block: { title: "수신자 Execute 최종 확인", intent: "Irreversible execute 직전 수신자 확정", risk: "되돌릴 수 없는 오발송", question: "수신자가 irreversible execute에 모호함 없이 확정되었습니까?" },
  payload_integrity_execute_final_block: { title: "Payload Integrity Execute 최종 확인", intent: "최종 payload 정합성 확인", risk: "되돌릴 수 없는 주문 착오", question: "Payload가 최종 run basis와 정합적입니까?" },
  reference_instruction_execute_final_block: { title: "Reference / Instruction Execute 최종 확인", intent: "Reference/instruction 최종 정합성", risk: "배송/입고 착오", question: "Reference와 instruction이 최종 basis와 정합적입니까?" },
  exclusion_guard_execute_final_block: { title: "Exclusion Guard Execute 최종 확인", intent: "Internal-only 최종 제외 확인", risk: "기밀 유출 — 되돌릴 수 없음", question: "Internal-only 문맥이 execute candidate에서 완전 제외되었습니까?" },
  actor_authorization_audit_execute_final_block: { title: "Actor / Authorization / Audit Execute 최종 확인", intent: "Execute actor authorization + audit chain 확인", risk: "Actor trace / audit chain gap 시 사후 추적 불가", question: "Actor authorization과 audit chain이 irreversible execute에 충분합니까?" },
  execute_completion_gate_review: { title: "Execute 완결성 확인", intent: "모든 execute block 완결 최종 검토", risk: "미확인 상태에서 fire 시 복구 불가", question: "모든 execute block이 완결되어 fire 준비가 되었습니까?" },
};

function buildExecSection(key: ExecuteSectionKey, rank: number, pkg: DispatchPreparationHandoffPackageV2, resolved: string[], unresolved: string[], warnings: string[]): ActualSendExecuteCheckSectionStateV2 {
  const m = META[key]; const status: ExecuteSectionStatus = unresolved.length > 0 ? "blocked" : warnings.length > 0 ? "warning" : "ready";
  return { sectionKey: key, sectionTitle: m.title, sectionStatus: status, priorityRank: rank, executeIntent: m.intent, whyThisMatters: m.risk, requiredExecuteInputs: [...resolved, ...unresolved], resolvedInputs: resolved, unresolvedOrAmbiguousInputs: unresolved, warnings, operatorActionRequired: unresolved.length > 0 ? `${m.title} 해소 필요` : warnings.length > 0 ? `${m.title} 검토` : `${m.title} 확인 가능`, canResolveInPlace: unresolved.length === 0, requiresReturnToActualSendRunReview: unresolved.length > 0, requiresReturnToExecutionOrCommitIfAny: false, nextBestActionLabel: unresolved.length > 0 ? `${m.title} 해소` : `${m.title} 확인`, payloadIntegrityBasis: key === "payload_integrity_execute_final_block" ? "direct" : "inherited", exclusionGuardBasis: key === "exclusion_guard_execute_final_block" ? "direct" : "inherited", actorAuthorizationBasis: key === "actor_authorization_audit_execute_final_block" ? "direct" : "inherited", auditChainBasis: key === "actor_authorization_audit_execute_final_block" ? "direct" : "inherited", irreversibleExecuteBasis: "execute_review" };
}

function deriveSections(pkg: DispatchPreparationHandoffPackageV2): ActualSendExecuteCheckSectionStateV2[] {
  const s: ActualSendExecuteCheckSectionStateV2[] = [];
  const rR: string[] = []; const rU: string[] = []; if (pkg.createdVendorId) rR.push("vendorId"); else rU.push("vendorId"); if (pkg.vendorContactReferenceVisible) rR.push("contact"); else rU.push("contact");
  s.push(buildExecSection("recipient_execute_final_block", 1, pkg, rR, rU, []));
  const pR: string[] = []; const pU: string[] = []; const pW: string[] = []; if (pkg.createdLineItems.length > 0) pR.push("lineItems"); else pU.push("lineItems"); if (pkg.createdAmountSummary) pR.push("amount"); else pW.push("amount 누락"); if (pkg.dispatchEligibleScope) pR.push("scope"); else pU.push("scope");
  s.push(buildExecSection("payload_integrity_execute_final_block", 2, pkg, pR, pU, pW));
  const refR: string[] = []; const refU: string[] = []; const refW: string[] = []; if (pkg.quoteReferenceVisible) refR.push("quote"); else refW.push("quote 비활성"); if (pkg.poReferenceVisible) refR.push("PO"); else refW.push("PO 비활성"); if (pkg.shipToVisible) refR.push("ship-to"); else refU.push("ship-to"); if (pkg.receivingInstructionVisible) refR.push("receiving"); else refW.push("receiving 비활성");
  s.push(buildExecSection("reference_instruction_execute_final_block", 3, pkg, refR, refU, refW));
  const eR: string[] = []; const eU: string[] = []; const eW: string[] = []; if (pkg.internalOnlyExcludedFlags.length > 0) eR.push(`${pkg.internalOnlyExcludedFlags.length}건 제외`); const seedLower = (pkg.supplierFacingNoteSeed || "").toLowerCase(); if (["budget", "governance", "internal", "approval"].some(kw => seedLower.includes(kw))) eU.push("contamination risk"); if (pkg.internalOnlyExcludedFlags.length === 0 && pkg.supplierFacingNoteSeed) eW.push("exclusion flag 없이 note seed 존재");
  s.push(buildExecSection("exclusion_guard_execute_final_block", 4, pkg, eR, eU, eW));
  const aR = ["actor_trace", "authorization", "audit_chain"]; const aW: string[] = []; if (pkg.provenanceByLine.length === 0) aW.push("provenance 누락");
  s.push(buildExecSection("actor_authorization_audit_execute_final_block", 5, pkg, aR, [], aW));
  const blocked = s.filter(x => x.sectionStatus === "blocked"); const warned = s.filter(x => x.sectionStatus === "warning");
  s.push(buildExecSection("execute_completion_gate_review", 6, pkg, s.filter(x => x.sectionStatus === "ready" || x.sectionStatus === "reviewed").map(x => x.sectionKey), blocked.map(x => `${x.sectionTitle} blocked`), warned.map(x => `${x.sectionTitle} warning`)));
  return s;
}

function deriveStatus(gate: ActualSendExecuteGateV2, secs: ActualSendExecuteCheckSectionStateV2[]): ExecuteWorkspaceStatus {
  if (gate.gateStatus !== "eligible_for_actual_send_execute" && gate.gateStatus !== "actual_send_execute_opened") return "locked_preview_only";
  const hasB = secs.some(x => x.sectionStatus === "blocked"); const hasW = secs.some(x => x.sectionStatus === "warning" || x.sectionStatus === "attention_required"); const allDone = secs.every(x => x.sectionStatus === "ready" || x.sectionStatus === "reviewed");
  if (allDone) return "execute_ready_pending_fire"; if (hasB) return "execute_review_required"; if (hasW) return "execute_review_in_progress"; return "entry_enabled";
}
function deriveMode(s: ExecuteWorkspaceStatus): ExecuteWorkspaceMode { switch (s) { case "locked_preview_only": return "preview_only"; case "entry_enabled": case "execute_review_required": return "execute_review"; case "execute_review_in_progress": return "irreversible_execute_check"; case "execute_hold": return "policy_review"; case "execute_review_pending": return "execute_review"; case "execute_ready_pending_fire": return "ready_pending_fire"; } }

const FOCUS: ExecuteSectionKey[] = ["recipient_execute_final_block", "payload_integrity_execute_final_block", "reference_instruction_execute_final_block", "exclusion_guard_execute_final_block", "actor_authorization_audit_execute_final_block", "execute_completion_gate_review"];
function deriveFocus(secs: ActualSendExecuteCheckSectionStateV2[]): ExecuteSectionKey[] { const b = FOCUS.filter(k => secs.find(x => x.sectionKey === k)?.sectionStatus === "blocked"); const w = FOCUS.filter(k => { const x = secs.find(s => s.sectionKey === k); return x && (x.sectionStatus === "warning" || x.sectionStatus === "attention_required") && !b.includes(k); }); const r = FOCUS.filter(k => !b.includes(k) && !w.includes(k)); return [...b, ...w, ...r]; }

export function buildActualSendExecuteWorkspaceStateV2(gate: ActualSendExecuteGateV2, pkg: DispatchPreparationHandoffPackageV2): ActualSendExecuteWorkspaceStateV2 {
  const secs = deriveSections(pkg); const status = deriveStatus(gate, secs); const mode = deriveMode(status); const focus = deriveFocus(secs);
  const isLocked = status === "locked_preview_only"; const isReady = status === "execute_ready_pending_fire"; const hasB = secs.some(x => x.sectionStatus === "blocked");
  const header: ActualSendExecuteWorkspaceHeaderV2 = { title: `Actual Send Execute — ${gate.caseId}`, statusChip: isLocked ? "Preview Only" : isReady ? "Execute Ready — Fire 대기" : hasB ? "차단됨" : "Execute 검토 가능", entryStatusLabel: isLocked ? "Entry Locked" : "Entry Enabled", entryStatusReason: isLocked ? gate.candidate.candidateReason : "Execute 가능", executeScopeLabel: gate.candidate.payloadIntegrityFinalSnapshot, currentGateLabel: "Actual Send Execute Control", nextGateLabel: "Actual Send Fire Action (Locked — Batch 1)", operatorMandate: isLocked ? "Preview only." : hasB ? "Execute 미확인 항목 해소 필요" : isReady ? "Execute ready — fire 활성화를 기다리세요." : "Execute 직전 각 항목 확인", lockInterpretation: isReady ? "Execute ready — fire는 아직 범위 밖" : isLocked ? "Gate 조건 미충족" : "Execute 검토 가능", actualSendFireLockReason: "Batch 1: Actual send fire, sent, dispatched 처리는 현재 범위 밖입니다" };
  const dock: ActualSendExecuteStickyDockStateV2 = { primaryAction: isLocked ? { label: "Preview Only", enabled: false, reason: "Entry locked" } : isReady ? { label: "Execute Ready — Fire 대기", enabled: false, reason: "Fire 활성화 대기" } : hasB ? { label: "미확인 해소", enabled: true, reason: "" } : { label: "Execute 검토 계속", enabled: true, reason: "" }, secondaryActions: [{ label: "Run Review로 복귀", enabled: true, reason: "" }, { label: "Hold 전환", enabled: true, reason: "" }, { label: "Section 확인 완료", enabled: !isLocked && !hasB, reason: hasB ? "Blocker 해소 필요" : "" }], disabledActions: [{ label: "Actual Send Fire", reason: "Batch 1 범위 밖" }, { label: "Mark Sent", reason: "Batch 1 범위 밖" }, { label: "Mark Dispatched", reason: "Batch 1 범위 밖" }, { label: "Delivery Tracking", reason: "Batch 1 범위 밖" }], blockedActionReasons: { execute_actual_send_fire: "Batch 1 금지", mark_sent: "Batch 1 금지", mark_dispatched: "Batch 1 금지", create_delivery_tracking: "Batch 1 금지" }, requiredResolutionBeforeProgress: hasB ? secs.find(x => x.sectionStatus === "blocked")?.sectionTitle ?? null : null, workspaceCompletionLabel: isReady ? "Execute ready — fire 대기" : "Execute 검토 진행 중", actualSendFireLockLabel: "Actual Send Fire — Batch 1 locked" };
  const previewMode: ExecutePreviewMode = isLocked ? "locked_preview" : isReady ? "execute_candidate_preview" : "review_preview";
  const cautions: string[] = []; if (!pkg.vendorContactReferenceVisible) cautions.push("Vendor contact 비활성"); if (!pkg.quoteReferenceVisible && !pkg.poReferenceVisible) cautions.push("Quote/PO 비활성"); if (pkg.internalOnlyExcludedFlags.length > 0) cautions.push(`${pkg.internalOnlyExcludedFlags.length}건 internal-only 제외`);
  const rail: ActualSendExecuteRightRailPreviewStateV2 = { previewMode, recipientPreview: { vendorId: pkg.createdVendorId, contactVisible: pkg.vendorContactReferenceVisible }, payloadIntegrityPreview: { lineCount: pkg.createdLineItems.length, amountSummary: pkg.createdAmountSummary, scopeIntact: !!pkg.dispatchEligibleScope }, referenceInstructionPreview: { quoteVisible: pkg.quoteReferenceVisible, poVisible: pkg.poReferenceVisible, shipToVisible: pkg.shipToVisible, receivingVisible: pkg.receivingInstructionVisible }, excludedInternalOnlyPreview: pkg.internalOnlyExcludedFlags, actorAuthorizationAuditPreview: { actorTraceComplete: pkg.provenanceByLine.length > 0, authorizationConfirmed: true, auditChainIntact: true }, previewCautionSummary: cautions.length > 0 ? cautions.join("; ") : "이슈 없음", provenancePreview: pkg.provenanceByLine.map(p => ({ candidateId: p.candidateId, lane: p.originalLane })) };
  const ak = focus[0] || null; const active = ak ? secs.find(x => x.sectionKey === ak) : null;
  const center: ActualSendExecuteCenterCanvasStateV2 = active ? { activeSectionKey: ak, decisionQuestion: META[ak!].question, executeContext: active.executeIntent, sourceInputSummary: `${active.resolvedInputs.length} resolved / ${active.unresolvedOrAmbiguousInputs.length} unresolved`, unresolvedOrConflictingInputs: [...active.unresolvedOrAmbiguousInputs, ...active.warnings], fieldGroups: active.requiredExecuteInputs.map(i => ({ groupKey: i, groupLabel: i, sourceMapping: "execute", resolved: active.resolvedInputs.includes(i), value: active.resolvedInputs.includes(i) ? "resolved" : "", unresolved: active.unresolvedOrAmbiguousInputs.includes(i), excluded: false })), riskSummary: META[ak!].risk, resolutionOptions: active.canResolveInPlace ? ["현재 workspace에서 확인 가능"] : ["Run review로 복귀 필요"], blockedDownstreamActions: ["execute_actual_send_fire", "mark_sent", "mark_dispatched"], completionRuleForSection: active.unresolvedOrAmbiguousInputs.length > 0 ? "미확인 해소 후 reviewed 가능" : "즉시 reviewed 가능" } : { activeSectionKey: null, decisionQuestion: "", executeContext: "", sourceInputSummary: "", unresolvedOrConflictingInputs: [], fieldGroups: [], riskSummary: "", resolutionOptions: [], blockedDownstreamActions: ["execute_actual_send_fire", "mark_sent", "mark_dispatched"], completionRuleForSection: "" };

  return { workspaceId: `execws_${Date.now().toString(36)}`, caseId: gate.caseId, handoffPackageId: gate.handoffPackageId, actualSendRunSessionId: gate.actualSendRunSessionId, actualSendExecuteGateId: gate.actualSendExecuteGateId, workspaceStatus: status, workspaceMode: mode, workspaceHeader: header, entryLockSummary: isLocked ? `Entry locked: ${gate.candidate.candidateReason}` : "Entry enabled", checkSectionStates: secs, activeSectionKey: ak, centerCanvasState: center, rightRailPreview: rail, stickyDock: dock, operatorFocusOrder: focus, provenance: pkg.provenanceByLine.map(p => ({ candidateId: p.candidateId, lane: p.originalLane })), generatedAt: new Date().toISOString() };
}

export type ExecuteWorkspaceEventType = "actual_send_execute_workspace_state_computed" | "actual_send_execute_workspace_opened_preview_only" | "actual_send_execute_workspace_entry_enabled" | "actual_send_execute_workspace_section_focused" | "actual_send_execute_workspace_section_review_started" | "actual_send_execute_workspace_marked_in_progress" | "actual_send_execute_workspace_marked_ready_pending_fire";
export interface ExecuteWorkspaceEvent { type: ExecuteWorkspaceEventType; caseId: string; handoffPackageId: string; actualSendRunSessionId: string; actualSendExecuteGateId: string; workspaceId: string; sectionKeyIfAny: ExecuteSectionKey | null; reason: string; actorOrSystem: string; timestamp: string; }
export function createExecuteWorkspaceEvent(type: ExecuteWorkspaceEventType, ws: ActualSendExecuteWorkspaceStateV2, sectionKey: ExecuteSectionKey | null, reason: string, actor: string): ExecuteWorkspaceEvent { return { type, caseId: ws.caseId, handoffPackageId: ws.handoffPackageId, actualSendRunSessionId: ws.actualSendRunSessionId, actualSendExecuteGateId: ws.actualSendExecuteGateId, workspaceId: ws.workspaceId, sectionKeyIfAny: sectionKey, reason, actorOrSystem: actor, timestamp: new Date().toISOString() }; }
