/**
 * Actual Send Commit Workspace v2 — final commit control surface contract
 *
 * 고정 규칙: commit ready ≠ sent ≠ dispatched. center/rail/dock 분리.
 * Batch 1: execute_actual_send_commit / mark_sent / mark_dispatched 금지.
 */

import type { ActualSendCommitGateV2, CommitGateStatus, ActualSendCommitCandidateV2 } from "./actual-send-commit-gate-v2-engine";
import type { DispatchPreparationHandoffPackageV2, InternalOnlyExcludedFlag } from "./dispatch-preparation-handoff-gate-v2-engine";

export type CommitWorkspaceStatus = "locked_preview_only" | "entry_enabled" | "commit_review_required" | "commit_review_in_progress" | "commit_hold" | "commit_review_pending" | "commit_ready_pending_execution";
export type CommitWorkspaceMode = "preview_only" | "commit_review" | "irreversible_commit_check" | "policy_review" | "ready_pending_execution";
export type CommitSectionKey = "recipient_commit_block" | "payload_integrity_commit_block" | "reference_instruction_commit_block" | "exclusion_guard_commit_block" | "actor_authorization_audit_commit_block" | "commit_completion_gate_review";
export type CommitSectionStatus = "ready" | "partial" | "warning" | "blocked" | "attention_required" | "reviewed";

export interface ActualSendCommitCheckSectionStateV2 { sectionKey: CommitSectionKey; sectionTitle: string; sectionStatus: CommitSectionStatus; priorityRank: number; commitIntent: string; whyThisMatters: string; requiredCommitInputs: string[]; resolvedInputs: string[]; unresolvedOrAmbiguousInputs: string[]; warnings: string[]; operatorActionRequired: string; canResolveInPlace: boolean; requiresReturnToActualSendTransactionReview: boolean; requiresReturnToActionOrExecutionIfAny: boolean; nextBestActionLabel: string; payloadIntegrityBasis: string; exclusionGuardBasis: string; actorAuthorizationBasis: string; auditChainBasis: string; irreversibleCommitBasis: string; }

export interface CommitFieldGroup { groupKey: string; groupLabel: string; sourceMapping: string; resolved: boolean; value: string; unresolved: boolean; excluded: boolean; }
export interface ActualSendCommitCenterCanvasStateV2 { activeSectionKey: CommitSectionKey | null; decisionQuestion: string; commitContext: string; sourceInputSummary: string; unresolvedOrConflictingInputs: string[]; fieldGroups: CommitFieldGroup[]; riskSummary: string; resolutionOptions: string[]; blockedDownstreamActions: string[]; completionRuleForSection: string; }

export type CommitPreviewMode = "locked_preview" | "commit_candidate_preview" | "warning_preview" | "review_preview";
export interface ActualSendCommitRightRailPreviewStateV2 { previewMode: CommitPreviewMode; recipientPreview: { vendorId: string; contactVisible: boolean }; payloadIntegrityPreview: { lineCount: number; amountSummary: string; scopeIntact: boolean }; referenceInstructionPreview: { quoteVisible: boolean; poVisible: boolean; shipToVisible: boolean; receivingVisible: boolean }; excludedInternalOnlyPreview: InternalOnlyExcludedFlag[]; actorAuthorizationAuditPreview: { actorTraceComplete: boolean; authorizationConfirmed: boolean; auditChainIntact: boolean }; previewCautionSummary: string; provenancePreview: { candidateId: string; lane: string }[]; }

export interface ActualSendCommitStickyDockStateV2 { primaryAction: { label: string; enabled: boolean; reason: string }; secondaryActions: { label: string; enabled: boolean; reason: string }[]; disabledActions: { label: string; reason: string }[]; blockedActionReasons: Record<string, string>; requiredResolutionBeforeProgress: string | null; workspaceCompletionLabel: string; actualSendExecutionLockLabel: string; }

export interface ActualSendCommitWorkspaceHeaderV2 { title: string; statusChip: string; entryStatusLabel: string; entryStatusReason: string; commitScopeLabel: string; currentGateLabel: string; nextGateLabel: string; operatorMandate: string; lockInterpretation: string; actualSendExecutionLockReason: string; }

export interface ActualSendCommitWorkspaceStateV2 {
  workspaceId: string; caseId: string; handoffPackageId: string; actualSendTransactionSessionId: string; actualSendCommitGateId: string;
  workspaceStatus: CommitWorkspaceStatus; workspaceMode: CommitWorkspaceMode;
  workspaceHeader: ActualSendCommitWorkspaceHeaderV2; entryLockSummary: string;
  checkSectionStates: ActualSendCommitCheckSectionStateV2[]; activeSectionKey: CommitSectionKey | null;
  centerCanvasState: ActualSendCommitCenterCanvasStateV2; rightRailPreview: ActualSendCommitRightRailPreviewStateV2; stickyDock: ActualSendCommitStickyDockStateV2;
  operatorFocusOrder: CommitSectionKey[]; provenance: { candidateId: string; lane: string }[]; generatedAt: string;
}

const META: Record<CommitSectionKey, { title: string; intent: string; risk: string; question: string }> = {
  recipient_commit_block: { title: "수신자 Commit 확인", intent: "Irreversible commit 직전 수신자 확정", risk: "되돌릴 수 없는 오발송", question: "수신자가 irreversible commit에 모호함 없이 확정되었습니까?" },
  payload_integrity_commit_block: { title: "Payload Integrity Commit 확인", intent: "최종 payload 정합성 확인", risk: "되돌릴 수 없는 주문 착오", question: "Payload가 최종 transaction basis와 정합적입니까?" },
  reference_instruction_commit_block: { title: "Reference / Instruction Commit 확인", intent: "Reference/instruction 최종 정합성", risk: "배송/입고 착오", question: "Reference와 instruction이 최종 basis와 정합적입니까?" },
  exclusion_guard_commit_block: { title: "Exclusion Guard Commit 확인", intent: "Internal-only 최종 제외 확인", risk: "기밀 유출 — 되돌릴 수 없음", question: "Internal-only 문맥이 commit candidate에서 완전 제외되었습니까?" },
  actor_authorization_audit_commit_block: { title: "Actor / Authorization / Audit Commit 확인", intent: "Commit actor authorization + audit chain 확인", risk: "Actor trace / audit chain gap 시 사후 추적 불가", question: "Actor authorization과 audit chain이 irreversible commit에 충분합니까?" },
  commit_completion_gate_review: { title: "Commit 완결성 확인", intent: "모든 commit block 완결 최종 검토", risk: "미확인 상태에서 execution 시 복구 불가", question: "모든 commit block이 완결되어 execution 준비가 되었습니까?" },
};

function buildCommitSection(key: CommitSectionKey, rank: number, pkg: DispatchPreparationHandoffPackageV2, resolved: string[], unresolved: string[], warnings: string[]): ActualSendCommitCheckSectionStateV2 {
  const m = META[key]; const status: CommitSectionStatus = unresolved.length > 0 ? "blocked" : warnings.length > 0 ? "warning" : "ready";
  return { sectionKey: key, sectionTitle: m.title, sectionStatus: status, priorityRank: rank, commitIntent: m.intent, whyThisMatters: m.risk, requiredCommitInputs: [...resolved, ...unresolved], resolvedInputs: resolved, unresolvedOrAmbiguousInputs: unresolved, warnings, operatorActionRequired: unresolved.length > 0 ? `${m.title} 해소 필요` : warnings.length > 0 ? `${m.title} 검토` : `${m.title} 확인 가능`, canResolveInPlace: unresolved.length === 0, requiresReturnToActualSendTransactionReview: unresolved.length > 0, requiresReturnToActionOrExecutionIfAny: false, nextBestActionLabel: unresolved.length > 0 ? `${m.title} 해소` : `${m.title} 확인`, payloadIntegrityBasis: key === "payload_integrity_commit_block" ? "direct" : "inherited", exclusionGuardBasis: key === "exclusion_guard_commit_block" ? "direct" : "inherited", actorAuthorizationBasis: key === "actor_authorization_audit_commit_block" ? "direct" : "inherited", auditChainBasis: key === "actor_authorization_audit_commit_block" ? "direct" : "inherited", irreversibleCommitBasis: "commit_review" };
}

function deriveSections(pkg: DispatchPreparationHandoffPackageV2): ActualSendCommitCheckSectionStateV2[] {
  const s: ActualSendCommitCheckSectionStateV2[] = [];
  const rR: string[] = []; const rU: string[] = []; if (pkg.createdVendorId) rR.push("vendorId"); else rU.push("vendorId"); if (pkg.vendorContactReferenceVisible) rR.push("contact"); else rU.push("contact");
  s.push(buildCommitSection("recipient_commit_block", 1, pkg, rR, rU, []));
  const pR: string[] = []; const pU: string[] = []; const pW: string[] = []; if (pkg.createdLineItems.length > 0) pR.push("lineItems"); else pU.push("lineItems"); if (pkg.createdAmountSummary) pR.push("amount"); else pW.push("amount 누락"); if (pkg.dispatchEligibleScope) pR.push("scope"); else pU.push("scope");
  s.push(buildCommitSection("payload_integrity_commit_block", 2, pkg, pR, pU, pW));
  const refR: string[] = []; const refU: string[] = []; const refW: string[] = []; if (pkg.quoteReferenceVisible) refR.push("quote"); else refW.push("quote 비활성"); if (pkg.poReferenceVisible) refR.push("PO"); else refW.push("PO 비활성"); if (pkg.shipToVisible) refR.push("ship-to"); else refU.push("ship-to"); if (pkg.receivingInstructionVisible) refR.push("receiving"); else refW.push("receiving 비활성");
  s.push(buildCommitSection("reference_instruction_commit_block", 3, pkg, refR, refU, refW));
  const eR: string[] = []; const eU: string[] = []; const eW: string[] = []; if (pkg.internalOnlyExcludedFlags.length > 0) eR.push(`${pkg.internalOnlyExcludedFlags.length}건 제외`); const seedLower = (pkg.supplierFacingNoteSeed || "").toLowerCase(); if (["budget", "governance", "internal", "approval"].some(kw => seedLower.includes(kw))) eU.push("contamination risk"); if (pkg.internalOnlyExcludedFlags.length === 0 && pkg.supplierFacingNoteSeed) eW.push("exclusion flag 없이 note seed 존재");
  s.push(buildCommitSection("exclusion_guard_commit_block", 4, pkg, eR, eU, eW));
  const aR = ["actor_trace", "authorization", "audit_chain"]; const aW: string[] = []; if (pkg.provenanceByLine.length === 0) aW.push("provenance 누락");
  s.push(buildCommitSection("actor_authorization_audit_commit_block", 5, pkg, aR, [], aW));
  const blocked = s.filter(x => x.sectionStatus === "blocked"); const warned = s.filter(x => x.sectionStatus === "warning");
  s.push(buildCommitSection("commit_completion_gate_review", 6, pkg, s.filter(x => x.sectionStatus === "ready" || x.sectionStatus === "reviewed").map(x => x.sectionKey), blocked.map(x => `${x.sectionTitle} blocked`), warned.map(x => `${x.sectionTitle} warning`)));
  return s;
}

function deriveStatus(gate: ActualSendCommitGateV2, secs: ActualSendCommitCheckSectionStateV2[]): CommitWorkspaceStatus {
  if (gate.gateStatus !== "eligible_for_actual_send_commit" && gate.gateStatus !== "actual_send_commit_opened") return "locked_preview_only";
  const hasB = secs.some(x => x.sectionStatus === "blocked"); const hasW = secs.some(x => x.sectionStatus === "warning" || x.sectionStatus === "attention_required"); const allDone = secs.every(x => x.sectionStatus === "ready" || x.sectionStatus === "reviewed");
  if (allDone) return "commit_ready_pending_execution"; if (hasB) return "commit_review_required"; if (hasW) return "commit_review_in_progress"; return "entry_enabled";
}
function deriveMode(s: CommitWorkspaceStatus): CommitWorkspaceMode { switch (s) { case "locked_preview_only": return "preview_only"; case "entry_enabled": case "commit_review_required": return "commit_review"; case "commit_review_in_progress": return "irreversible_commit_check"; case "commit_hold": return "policy_review"; case "commit_review_pending": return "commit_review"; case "commit_ready_pending_execution": return "ready_pending_execution"; } }

const FOCUS: CommitSectionKey[] = ["recipient_commit_block", "payload_integrity_commit_block", "reference_instruction_commit_block", "exclusion_guard_commit_block", "actor_authorization_audit_commit_block", "commit_completion_gate_review"];
function deriveFocus(secs: ActualSendCommitCheckSectionStateV2[]): CommitSectionKey[] { const b = FOCUS.filter(k => secs.find(x => x.sectionKey === k)?.sectionStatus === "blocked"); const w = FOCUS.filter(k => { const x = secs.find(s => s.sectionKey === k); return x && (x.sectionStatus === "warning" || x.sectionStatus === "attention_required") && !b.includes(k); }); const r = FOCUS.filter(k => !b.includes(k) && !w.includes(k)); return [...b, ...w, ...r]; }

export function buildActualSendCommitWorkspaceStateV2(gate: ActualSendCommitGateV2, pkg: DispatchPreparationHandoffPackageV2): ActualSendCommitWorkspaceStateV2 {
  const secs = deriveSections(pkg); const status = deriveStatus(gate, secs); const mode = deriveMode(status); const focus = deriveFocus(secs);
  const isLocked = status === "locked_preview_only"; const isReady = status === "commit_ready_pending_execution"; const hasB = secs.some(x => x.sectionStatus === "blocked");
  const header: ActualSendCommitWorkspaceHeaderV2 = { title: `Actual Send Commit — ${gate.caseId}`, statusChip: isLocked ? "Preview Only" : isReady ? "Commit Ready — Execution 대기" : hasB ? "차단됨" : "Commit 검토 가능", entryStatusLabel: isLocked ? "Entry Locked" : "Entry Enabled", entryStatusReason: isLocked ? gate.candidate.candidateReason : "Commit 가능", commitScopeLabel: gate.candidate.payloadIntegrityFinalSnapshot, currentGateLabel: "Actual Send Commit Control", nextGateLabel: "Actual Send Commit Execution (Locked — Batch 1)", operatorMandate: isLocked ? "Preview only." : hasB ? "Commit 미확인 항목 해소 필요" : isReady ? "Commit ready — execution 활성화를 기다리세요." : "Commit 직전 각 항목 확인", lockInterpretation: isReady ? "Commit ready — execution은 아직 범위 밖" : isLocked ? "Gate 조건 미충족" : "Commit 검토 가능", actualSendExecutionLockReason: "Batch 1: Actual send commit execution, sent, dispatched 처리는 현재 범위 밖입니다" };
  const dock: ActualSendCommitStickyDockStateV2 = { primaryAction: isLocked ? { label: "Preview Only", enabled: false, reason: "Entry locked" } : isReady ? { label: "Commit Ready — Execution 대기", enabled: false, reason: "Execution 활성화 대기" } : hasB ? { label: "미확인 해소", enabled: true, reason: "" } : { label: "Commit 검토 계속", enabled: true, reason: "" }, secondaryActions: [{ label: "Transaction Review로 복귀", enabled: true, reason: "" }, { label: "Hold 전환", enabled: true, reason: "" }, { label: "Section 확인 완료", enabled: !isLocked && !hasB, reason: hasB ? "Blocker 해소 필요" : "" }], disabledActions: [{ label: "Actual Send Commit Execution", reason: "Batch 1 범위 밖" }, { label: "Mark Sent", reason: "Batch 1 범위 밖" }, { label: "Mark Dispatched", reason: "Batch 1 범위 밖" }, { label: "Delivery Tracking", reason: "Batch 1 범위 밖" }], blockedActionReasons: { execute_actual_send_commit: "Batch 1 금지", mark_sent: "Batch 1 금지", mark_dispatched: "Batch 1 금지", create_delivery_tracking: "Batch 1 금지" }, requiredResolutionBeforeProgress: hasB ? secs.find(x => x.sectionStatus === "blocked")?.sectionTitle ?? null : null, workspaceCompletionLabel: isReady ? "Commit ready — execution 대기" : "Commit 검토 진행 중", actualSendExecutionLockLabel: "Actual Send Commit Execution — Batch 1 locked" };
  const previewMode: CommitPreviewMode = isLocked ? "locked_preview" : isReady ? "commit_candidate_preview" : "review_preview";
  const cautions: string[] = []; if (!pkg.vendorContactReferenceVisible) cautions.push("Vendor contact 비활성"); if (!pkg.quoteReferenceVisible && !pkg.poReferenceVisible) cautions.push("Quote/PO 비활성"); if (pkg.internalOnlyExcludedFlags.length > 0) cautions.push(`${pkg.internalOnlyExcludedFlags.length}건 internal-only 제외`);
  const rail: ActualSendCommitRightRailPreviewStateV2 = { previewMode, recipientPreview: { vendorId: pkg.createdVendorId, contactVisible: pkg.vendorContactReferenceVisible }, payloadIntegrityPreview: { lineCount: pkg.createdLineItems.length, amountSummary: pkg.createdAmountSummary, scopeIntact: !!pkg.dispatchEligibleScope }, referenceInstructionPreview: { quoteVisible: pkg.quoteReferenceVisible, poVisible: pkg.poReferenceVisible, shipToVisible: pkg.shipToVisible, receivingVisible: pkg.receivingInstructionVisible }, excludedInternalOnlyPreview: pkg.internalOnlyExcludedFlags, actorAuthorizationAuditPreview: { actorTraceComplete: pkg.provenanceByLine.length > 0, authorizationConfirmed: true, auditChainIntact: true }, previewCautionSummary: cautions.length > 0 ? cautions.join("; ") : "이슈 없음", provenancePreview: pkg.provenanceByLine.map(p => ({ candidateId: p.candidateId, lane: p.originalLane })) };
  const ak = focus[0] || null; const active = ak ? secs.find(x => x.sectionKey === ak) : null;
  const center: ActualSendCommitCenterCanvasStateV2 = active ? { activeSectionKey: ak, decisionQuestion: META[ak!].question, commitContext: active.commitIntent, sourceInputSummary: `${active.resolvedInputs.length} resolved / ${active.unresolvedOrAmbiguousInputs.length} unresolved`, unresolvedOrConflictingInputs: [...active.unresolvedOrAmbiguousInputs, ...active.warnings], fieldGroups: active.requiredCommitInputs.map(i => ({ groupKey: i, groupLabel: i, sourceMapping: "commit", resolved: active.resolvedInputs.includes(i), value: active.resolvedInputs.includes(i) ? "resolved" : "", unresolved: active.unresolvedOrAmbiguousInputs.includes(i), excluded: false })), riskSummary: META[ak!].risk, resolutionOptions: active.canResolveInPlace ? ["현재 workspace에서 확인 가능"] : ["Transaction review로 복귀 필요"], blockedDownstreamActions: ["execute_actual_send_commit", "mark_sent", "mark_dispatched"], completionRuleForSection: active.unresolvedOrAmbiguousInputs.length > 0 ? "미확인 해소 후 reviewed 가능" : "즉시 reviewed 가능" } : { activeSectionKey: null, decisionQuestion: "", commitContext: "", sourceInputSummary: "", unresolvedOrConflictingInputs: [], fieldGroups: [], riskSummary: "", resolutionOptions: [], blockedDownstreamActions: ["execute_actual_send_commit", "mark_sent", "mark_dispatched"], completionRuleForSection: "" };

  return { workspaceId: `cmtws_${Date.now().toString(36)}`, caseId: gate.caseId, handoffPackageId: gate.handoffPackageId, actualSendTransactionSessionId: gate.actualSendTransactionSessionId, actualSendCommitGateId: gate.actualSendCommitGateId, workspaceStatus: status, workspaceMode: mode, workspaceHeader: header, entryLockSummary: isLocked ? `Entry locked: ${gate.candidate.candidateReason}` : "Entry enabled", checkSectionStates: secs, activeSectionKey: ak, centerCanvasState: center, rightRailPreview: rail, stickyDock: dock, operatorFocusOrder: focus, provenance: pkg.provenanceByLine.map(p => ({ candidateId: p.candidateId, lane: p.originalLane })), generatedAt: new Date().toISOString() };
}

export type CommitWorkspaceEventType = "actual_send_commit_workspace_state_computed" | "actual_send_commit_workspace_opened_preview_only" | "actual_send_commit_workspace_entry_enabled" | "actual_send_commit_workspace_section_focused" | "actual_send_commit_workspace_section_review_started" | "actual_send_commit_workspace_marked_in_progress" | "actual_send_commit_workspace_marked_ready_pending_execution";
export interface CommitWorkspaceEvent { type: CommitWorkspaceEventType; caseId: string; handoffPackageId: string; actualSendTransactionSessionId: string; actualSendCommitGateId: string; workspaceId: string; sectionKeyIfAny: CommitSectionKey | null; reason: string; actorOrSystem: string; timestamp: string; }
export function createCommitWorkspaceEvent(type: CommitWorkspaceEventType, ws: ActualSendCommitWorkspaceStateV2, sectionKey: CommitSectionKey | null, reason: string, actor: string): CommitWorkspaceEvent { return { type, caseId: ws.caseId, handoffPackageId: ws.handoffPackageId, actualSendTransactionSessionId: ws.actualSendTransactionSessionId, actualSendCommitGateId: ws.actualSendCommitGateId, workspaceId: ws.workspaceId, sectionKeyIfAny: sectionKey, reason, actorOrSystem: actor, timestamp: new Date().toISOString() }; }
