/**
 * Actual Send Fire Workspace v2 — absolute final fire control surface
 *
 * Batch 1 absolute terminal workspace. fire ready ≠ fired ≠ sent ≠ dispatched.
 * After this: Batch 2 actual fire mutation → sent → dispatched → tracking.
 */

import type { ActualSendFireGateV2, FireGateStatus, ActualSendFireCandidateV2 } from "./actual-send-fire-gate-v2-engine";
import type { DispatchPreparationHandoffPackageV2, InternalOnlyExcludedFlag } from "./dispatch-preparation-handoff-gate-v2-engine";

export type FireWorkspaceStatus = "locked_preview_only" | "entry_enabled" | "fire_review_required" | "fire_review_in_progress" | "fire_hold" | "fire_review_pending" | "fire_ready_pending_ignition";
export type FireWorkspaceMode = "preview_only" | "fire_review" | "irreversible_fire_check" | "policy_review" | "ready_pending_ignition";
export type FireSectionKey = "recipient_fire_final_block" | "payload_integrity_fire_final_block" | "reference_instruction_fire_final_block" | "exclusion_guard_fire_final_block" | "actor_authorization_audit_fire_final_block" | "fire_completion_gate_review";
export type FireSectionStatus = "ready" | "partial" | "warning" | "blocked" | "attention_required" | "reviewed";

export interface ActualSendFireCheckSectionStateV2 { sectionKey: FireSectionKey; sectionTitle: string; sectionStatus: FireSectionStatus; priorityRank: number; fireIntent: string; whyThisMatters: string; requiredFireInputs: string[]; resolvedInputs: string[]; unresolvedOrAmbiguousInputs: string[]; warnings: string[]; operatorActionRequired: string; canResolveInPlace: boolean; requiresReturnToActualSendExecuteReview: boolean; requiresReturnToRunOrCommitIfAny: boolean; nextBestActionLabel: string; payloadIntegrityBasis: string; exclusionGuardBasis: string; actorAuthorizationBasis: string; auditChainBasis: string; irreversibleFireBasis: string; }

export interface FireFieldGroup { groupKey: string; groupLabel: string; sourceMapping: string; resolved: boolean; value: string; unresolved: boolean; excluded: boolean; }
export interface ActualSendFireCenterCanvasStateV2 { activeSectionKey: FireSectionKey | null; decisionQuestion: string; fireContext: string; sourceInputSummary: string; unresolvedOrConflictingInputs: string[]; fieldGroups: FireFieldGroup[]; riskSummary: string; resolutionOptions: string[]; blockedDownstreamActions: string[]; completionRuleForSection: string; }

export type FirePreviewMode = "locked_preview" | "fire_candidate_preview" | "warning_preview" | "review_preview";
export interface ActualSendFireRightRailPreviewStateV2 { previewMode: FirePreviewMode; recipientPreview: { vendorId: string; contactVisible: boolean }; payloadIntegrityPreview: { lineCount: number; amountSummary: string; scopeIntact: boolean }; referenceInstructionPreview: { quoteVisible: boolean; poVisible: boolean; shipToVisible: boolean; receivingVisible: boolean }; excludedInternalOnlyPreview: InternalOnlyExcludedFlag[]; actorAuthorizationAuditPreview: { actorTraceComplete: boolean; authorizationConfirmed: boolean; auditChainIntact: boolean }; previewCautionSummary: string; provenancePreview: { candidateId: string; lane: string }[]; }

export interface ActualSendFireStickyDockStateV2 { primaryAction: { label: string; enabled: boolean; reason: string }; secondaryActions: { label: string; enabled: boolean; reason: string }[]; disabledActions: { label: string; reason: string }[]; blockedActionReasons: Record<string, string>; requiredResolutionBeforeProgress: string | null; workspaceCompletionLabel: string; actualSendIgnitionLockLabel: string; }

export interface ActualSendFireWorkspaceHeaderV2 { title: string; statusChip: string; entryStatusLabel: string; entryStatusReason: string; fireScopeLabel: string; currentGateLabel: string; nextGateLabel: string; operatorMandate: string; lockInterpretation: string; actualSendIgnitionLockReason: string; }

export interface ActualSendFireWorkspaceStateV2 {
  workspaceId: string; caseId: string; handoffPackageId: string; actualSendExecuteSessionId: string; actualSendFireGateId: string;
  workspaceStatus: FireWorkspaceStatus; workspaceMode: FireWorkspaceMode;
  workspaceHeader: ActualSendFireWorkspaceHeaderV2; entryLockSummary: string;
  checkSectionStates: ActualSendFireCheckSectionStateV2[]; activeSectionKey: FireSectionKey | null;
  centerCanvasState: ActualSendFireCenterCanvasStateV2; rightRailPreview: ActualSendFireRightRailPreviewStateV2; stickyDock: ActualSendFireStickyDockStateV2;
  operatorFocusOrder: FireSectionKey[]; provenance: { candidateId: string; lane: string }[]; generatedAt: string;
}

const META: Record<FireSectionKey, { title: string; intent: string; risk: string; question: string }> = {
  recipient_fire_final_block: { title: "수신자 Fire 최종 확인", intent: "Irreversible fire 직전 수신자 확정", risk: "되돌릴 수 없는 오발송", question: "수신자가 irreversible fire에 모호함 없이 확정되었습니까?" },
  payload_integrity_fire_final_block: { title: "Payload Integrity Fire 최종 확인", intent: "최종 payload 정합성 확인", risk: "되돌릴 수 없는 주문 착오", question: "Payload가 최종 execute basis와 정합적입니까?" },
  reference_instruction_fire_final_block: { title: "Reference / Instruction Fire 최종 확인", intent: "Reference/instruction 최종 정합성", risk: "배송/입고 착오", question: "Reference와 instruction이 최종 basis와 정합적입니까?" },
  exclusion_guard_fire_final_block: { title: "Exclusion Guard Fire 최종 확인", intent: "Internal-only 최종 제외 확인", risk: "기밀 유출 — 되돌릴 수 없음", question: "Internal-only 문맥이 fire candidate에서 완전 제외되었습니까?" },
  actor_authorization_audit_fire_final_block: { title: "Actor / Authorization / Audit Fire 최종 확인", intent: "Fire actor authorization + audit chain 확인", risk: "Actor trace / audit chain gap 시 사후 추적 불가", question: "Actor authorization과 audit chain이 irreversible fire에 충분합니까?" },
  fire_completion_gate_review: { title: "Fire 완결성 확인", intent: "모든 fire block 완결 최종 검토", risk: "미확인 상태에서 ignition 시 복구 불가", question: "모든 fire block이 완결되어 ignition 준비가 되었습니까?" },
};

function buildFireSection(key: FireSectionKey, rank: number, pkg: DispatchPreparationHandoffPackageV2, resolved: string[], unresolved: string[], warnings: string[]): ActualSendFireCheckSectionStateV2 {
  const m = META[key]; const status: FireSectionStatus = unresolved.length > 0 ? "blocked" : warnings.length > 0 ? "warning" : "ready";
  return { sectionKey: key, sectionTitle: m.title, sectionStatus: status, priorityRank: rank, fireIntent: m.intent, whyThisMatters: m.risk, requiredFireInputs: [...resolved, ...unresolved], resolvedInputs: resolved, unresolvedOrAmbiguousInputs: unresolved, warnings, operatorActionRequired: unresolved.length > 0 ? `${m.title} 해소 필요` : warnings.length > 0 ? `${m.title} 검토` : `${m.title} 확인 가능`, canResolveInPlace: unresolved.length === 0, requiresReturnToActualSendExecuteReview: unresolved.length > 0, requiresReturnToRunOrCommitIfAny: false, nextBestActionLabel: unresolved.length > 0 ? `${m.title} 해소` : `${m.title} 확인`, payloadIntegrityBasis: key === "payload_integrity_fire_final_block" ? "direct" : "inherited", exclusionGuardBasis: key === "exclusion_guard_fire_final_block" ? "direct" : "inherited", actorAuthorizationBasis: key === "actor_authorization_audit_fire_final_block" ? "direct" : "inherited", auditChainBasis: key === "actor_authorization_audit_fire_final_block" ? "direct" : "inherited", irreversibleFireBasis: "fire_review" };
}

function deriveSections(pkg: DispatchPreparationHandoffPackageV2): ActualSendFireCheckSectionStateV2[] {
  const s: ActualSendFireCheckSectionStateV2[] = [];
  const rR: string[] = []; const rU: string[] = []; if (pkg.createdVendorId) rR.push("vendorId"); else rU.push("vendorId"); if (pkg.vendorContactReferenceVisible) rR.push("contact"); else rU.push("contact");
  s.push(buildFireSection("recipient_fire_final_block", 1, pkg, rR, rU, []));
  const pR: string[] = []; const pU: string[] = []; const pW: string[] = []; if (pkg.createdLineItems.length > 0) pR.push("lineItems"); else pU.push("lineItems"); if (pkg.createdAmountSummary) pR.push("amount"); else pW.push("amount 누락"); if (pkg.dispatchEligibleScope) pR.push("scope"); else pU.push("scope");
  s.push(buildFireSection("payload_integrity_fire_final_block", 2, pkg, pR, pU, pW));
  const refR: string[] = []; const refU: string[] = []; const refW: string[] = []; if (pkg.quoteReferenceVisible) refR.push("quote"); else refW.push("quote 비활성"); if (pkg.poReferenceVisible) refR.push("PO"); else refW.push("PO 비활성"); if (pkg.shipToVisible) refR.push("ship-to"); else refU.push("ship-to"); if (pkg.receivingInstructionVisible) refR.push("receiving"); else refW.push("receiving 비활성");
  s.push(buildFireSection("reference_instruction_fire_final_block", 3, pkg, refR, refU, refW));
  const eR: string[] = []; const eU: string[] = []; const eW: string[] = []; if (pkg.internalOnlyExcludedFlags.length > 0) eR.push(`${pkg.internalOnlyExcludedFlags.length}건 제외`); const seedLower = (pkg.supplierFacingNoteSeed || "").toLowerCase(); if (["budget", "governance", "internal", "approval"].some(kw => seedLower.includes(kw))) eU.push("contamination risk"); if (pkg.internalOnlyExcludedFlags.length === 0 && pkg.supplierFacingNoteSeed) eW.push("exclusion flag 없이 note seed 존재");
  s.push(buildFireSection("exclusion_guard_fire_final_block", 4, pkg, eR, eU, eW));
  const aR = ["actor_trace", "authorization", "audit_chain"]; const aW: string[] = []; if (pkg.provenanceByLine.length === 0) aW.push("provenance 누락");
  s.push(buildFireSection("actor_authorization_audit_fire_final_block", 5, pkg, aR, [], aW));
  const blocked = s.filter(x => x.sectionStatus === "blocked"); const warned = s.filter(x => x.sectionStatus === "warning");
  s.push(buildFireSection("fire_completion_gate_review", 6, pkg, s.filter(x => x.sectionStatus === "ready" || x.sectionStatus === "reviewed").map(x => x.sectionKey), blocked.map(x => `${x.sectionTitle} blocked`), warned.map(x => `${x.sectionTitle} warning`)));
  return s;
}

function deriveStatus(gate: ActualSendFireGateV2, secs: ActualSendFireCheckSectionStateV2[]): FireWorkspaceStatus {
  if (gate.gateStatus !== "eligible_for_actual_send_fire" && gate.gateStatus !== "actual_send_fire_opened") return "locked_preview_only";
  const hasB = secs.some(x => x.sectionStatus === "blocked"); const hasW = secs.some(x => x.sectionStatus === "warning" || x.sectionStatus === "attention_required"); const allDone = secs.every(x => x.sectionStatus === "ready" || x.sectionStatus === "reviewed");
  if (allDone) return "fire_ready_pending_ignition"; if (hasB) return "fire_review_required"; if (hasW) return "fire_review_in_progress"; return "entry_enabled";
}
function deriveMode(s: FireWorkspaceStatus): FireWorkspaceMode { switch (s) { case "locked_preview_only": return "preview_only"; case "entry_enabled": case "fire_review_required": return "fire_review"; case "fire_review_in_progress": return "irreversible_fire_check"; case "fire_hold": return "policy_review"; case "fire_review_pending": return "fire_review"; case "fire_ready_pending_ignition": return "ready_pending_ignition"; } }

const FOCUS: FireSectionKey[] = ["recipient_fire_final_block", "payload_integrity_fire_final_block", "reference_instruction_fire_final_block", "exclusion_guard_fire_final_block", "actor_authorization_audit_fire_final_block", "fire_completion_gate_review"];
function deriveFocus(secs: ActualSendFireCheckSectionStateV2[]): FireSectionKey[] { const b = FOCUS.filter(k => secs.find(x => x.sectionKey === k)?.sectionStatus === "blocked"); const w = FOCUS.filter(k => { const x = secs.find(s => s.sectionKey === k); return x && (x.sectionStatus === "warning" || x.sectionStatus === "attention_required") && !b.includes(k); }); const r = FOCUS.filter(k => !b.includes(k) && !w.includes(k)); return [...b, ...w, ...r]; }

export function buildActualSendFireWorkspaceStateV2(gate: ActualSendFireGateV2, pkg: DispatchPreparationHandoffPackageV2): ActualSendFireWorkspaceStateV2 {
  const secs = deriveSections(pkg); const status = deriveStatus(gate, secs); const mode = deriveMode(status); const focus = deriveFocus(secs);
  const isLocked = status === "locked_preview_only"; const isReady = status === "fire_ready_pending_ignition"; const hasB = secs.some(x => x.sectionStatus === "blocked");
  const header: ActualSendFireWorkspaceHeaderV2 = { title: `Actual Send Fire — ${gate.caseId}`, statusChip: isLocked ? "Preview Only" : isReady ? "Fire Ready — Ignition 대기" : hasB ? "차단됨" : "Fire 검토 가능", entryStatusLabel: isLocked ? "Entry Locked" : "Entry Enabled", entryStatusReason: isLocked ? gate.candidate.candidateReason : "Fire 가능", fireScopeLabel: gate.candidate.payloadIntegrityFinalSnapshot, currentGateLabel: "Actual Send Fire Control", nextGateLabel: "Actual Send Ignition (Locked — Batch 1 Terminal)", operatorMandate: isLocked ? "Preview only." : hasB ? "Fire 미확인 항목 해소 필요" : isReady ? "Fire ready — Batch 1 terminal. Ignition은 Batch 2에서 활성화됩니다." : "Fire 직전 각 항목 확인", lockInterpretation: isReady ? "Fire ready — ignition은 Batch 2 영역" : isLocked ? "Gate 조건 미충족" : "Fire 검토 가능", actualSendIgnitionLockReason: "Batch 1 Terminal: Actual send ignition, sent, dispatched 처리는 Batch 2에서 처리됩니다" };
  const dock: ActualSendFireStickyDockStateV2 = { primaryAction: isLocked ? { label: "Preview Only", enabled: false, reason: "Entry locked" } : isReady ? { label: "Fire Ready — Batch 1 Terminal", enabled: false, reason: "Ignition은 Batch 2 영역" } : hasB ? { label: "미확인 해소", enabled: true, reason: "" } : { label: "Fire 검토 계속", enabled: true, reason: "" }, secondaryActions: [{ label: "Execute Review로 복귀", enabled: true, reason: "" }, { label: "Hold 전환", enabled: true, reason: "" }, { label: "Section 확인 완료", enabled: !isLocked && !hasB, reason: hasB ? "Blocker 해소 필요" : "" }], disabledActions: [{ label: "Actual Send Ignition", reason: "Batch 1 Terminal" }, { label: "Mark Sent", reason: "Batch 1 Terminal" }, { label: "Mark Dispatched", reason: "Batch 1 Terminal" }, { label: "Delivery Tracking", reason: "Batch 1 Terminal" }], blockedActionReasons: { execute_actual_send_ignition: "Batch 1 Terminal", mark_sent: "Batch 1 Terminal", mark_dispatched: "Batch 1 Terminal", create_delivery_tracking: "Batch 1 Terminal" }, requiredResolutionBeforeProgress: hasB ? secs.find(x => x.sectionStatus === "blocked")?.sectionTitle ?? null : null, workspaceCompletionLabel: isReady ? "Fire ready — Batch 1 terminal reached" : "Fire 검토 진행 중", actualSendIgnitionLockLabel: "Actual Send Ignition — Batch 2" };
  const previewMode: FirePreviewMode = isLocked ? "locked_preview" : isReady ? "fire_candidate_preview" : "review_preview";
  const cautions: string[] = []; if (!pkg.vendorContactReferenceVisible) cautions.push("Vendor contact 비활성"); if (!pkg.quoteReferenceVisible && !pkg.poReferenceVisible) cautions.push("Quote/PO 비활성"); if (pkg.internalOnlyExcludedFlags.length > 0) cautions.push(`${pkg.internalOnlyExcludedFlags.length}건 internal-only 제외`);
  const rail: ActualSendFireRightRailPreviewStateV2 = { previewMode, recipientPreview: { vendorId: pkg.createdVendorId, contactVisible: pkg.vendorContactReferenceVisible }, payloadIntegrityPreview: { lineCount: pkg.createdLineItems.length, amountSummary: pkg.createdAmountSummary, scopeIntact: !!pkg.dispatchEligibleScope }, referenceInstructionPreview: { quoteVisible: pkg.quoteReferenceVisible, poVisible: pkg.poReferenceVisible, shipToVisible: pkg.shipToVisible, receivingVisible: pkg.receivingInstructionVisible }, excludedInternalOnlyPreview: pkg.internalOnlyExcludedFlags, actorAuthorizationAuditPreview: { actorTraceComplete: pkg.provenanceByLine.length > 0, authorizationConfirmed: true, auditChainIntact: true }, previewCautionSummary: cautions.length > 0 ? cautions.join("; ") : "이슈 없음", provenancePreview: pkg.provenanceByLine.map(p => ({ candidateId: p.candidateId, lane: p.originalLane })) };
  const ak = focus[0] || null; const active = ak ? secs.find(x => x.sectionKey === ak) : null;
  const center: ActualSendFireCenterCanvasStateV2 = active ? { activeSectionKey: ak, decisionQuestion: META[ak!].question, fireContext: active.fireIntent, sourceInputSummary: `${active.resolvedInputs.length} resolved / ${active.unresolvedOrAmbiguousInputs.length} unresolved`, unresolvedOrConflictingInputs: [...active.unresolvedOrAmbiguousInputs, ...active.warnings], fieldGroups: active.requiredFireInputs.map(i => ({ groupKey: i, groupLabel: i, sourceMapping: "fire", resolved: active.resolvedInputs.includes(i), value: active.resolvedInputs.includes(i) ? "resolved" : "", unresolved: active.unresolvedOrAmbiguousInputs.includes(i), excluded: false })), riskSummary: META[ak!].risk, resolutionOptions: active.canResolveInPlace ? ["현재 workspace에서 확인 가능"] : ["Execute review로 복귀 필요"], blockedDownstreamActions: ["execute_actual_send_ignition", "mark_sent", "mark_dispatched"], completionRuleForSection: active.unresolvedOrAmbiguousInputs.length > 0 ? "미확인 해소 후 reviewed 가능" : "즉시 reviewed 가능" } : { activeSectionKey: null, decisionQuestion: "", fireContext: "", sourceInputSummary: "", unresolvedOrConflictingInputs: [], fieldGroups: [], riskSummary: "", resolutionOptions: [], blockedDownstreamActions: ["execute_actual_send_ignition", "mark_sent", "mark_dispatched"], completionRuleForSection: "" };

  return { workspaceId: `firews_${Date.now().toString(36)}`, caseId: gate.caseId, handoffPackageId: gate.handoffPackageId, actualSendExecuteSessionId: gate.actualSendExecuteSessionId, actualSendFireGateId: gate.actualSendFireGateId, workspaceStatus: status, workspaceMode: mode, workspaceHeader: header, entryLockSummary: isLocked ? `Entry locked: ${gate.candidate.candidateReason}` : "Entry enabled", checkSectionStates: secs, activeSectionKey: ak, centerCanvasState: center, rightRailPreview: rail, stickyDock: dock, operatorFocusOrder: focus, provenance: pkg.provenanceByLine.map(p => ({ candidateId: p.candidateId, lane: p.originalLane })), generatedAt: new Date().toISOString() };
}

export type FireWorkspaceEventType = "actual_send_fire_workspace_state_computed" | "actual_send_fire_workspace_opened_preview_only" | "actual_send_fire_workspace_entry_enabled" | "actual_send_fire_workspace_section_focused" | "actual_send_fire_workspace_section_review_started" | "actual_send_fire_workspace_marked_in_progress" | "actual_send_fire_workspace_marked_ready_pending_ignition";
export interface FireWorkspaceEvent { type: FireWorkspaceEventType; caseId: string; handoffPackageId: string; actualSendExecuteSessionId: string; actualSendFireGateId: string; workspaceId: string; sectionKeyIfAny: FireSectionKey | null; reason: string; actorOrSystem: string; timestamp: string; }
export function createFireWorkspaceEvent(type: FireWorkspaceEventType, ws: ActualSendFireWorkspaceStateV2, sectionKey: FireSectionKey | null, reason: string, actor: string): FireWorkspaceEvent { return { type, caseId: ws.caseId, handoffPackageId: ws.handoffPackageId, actualSendExecuteSessionId: ws.actualSendExecuteSessionId, actualSendFireGateId: ws.actualSendFireGateId, workspaceId: ws.workspaceId, sectionKeyIfAny: sectionKey, reason, actorOrSystem: actor, timestamp: new Date().toISOString() }; }
