/**
 * Actual Send Transaction Workspace v2 — final transaction control surface contract
 *
 * 고정 규칙: transaction ready ≠ sent ≠ dispatched. center/rail/dock 분리.
 * Batch 1: execute/mark_sent/mark_dispatched 금지.
 */

import type { ActualSendTransactionGateV2, TransactionGateStatus, ActualSendTransactionCandidateV2 } from "./actual-send-transaction-gate-v2-engine";
import type { DispatchPreparationHandoffPackageV2, InternalOnlyExcludedFlag } from "./dispatch-preparation-handoff-gate-v2-engine";

export type TransactionWorkspaceStatus = "locked_preview_only" | "entry_enabled" | "transaction_review_required" | "transaction_review_in_progress" | "transaction_hold" | "transaction_review_pending" | "transaction_ready_pending_commit";
export type TransactionWorkspaceMode = "preview_only" | "transaction_review" | "irreversible_commit_check" | "policy_review" | "ready_pending_commit";
export type TransactionSectionKey = "recipient_transaction_block" | "payload_integrity_transaction_block" | "reference_instruction_transaction_block" | "exclusion_guard_transaction_block" | "actor_authorization_audit_transaction_block" | "transaction_completion_gate_review";
export type TransactionSectionStatus = "ready" | "partial" | "warning" | "blocked" | "attention_required" | "reviewed";

export interface ActualSendTransactionCheckSectionStateV2 { sectionKey: TransactionSectionKey; sectionTitle: string; sectionStatus: TransactionSectionStatus; priorityRank: number; transactionIntent: string; whyThisMatters: string; requiredTransactionInputs: string[]; resolvedInputs: string[]; unresolvedOrAmbiguousInputs: string[]; warnings: string[]; operatorActionRequired: string; canResolveInPlace: boolean; requiresReturnToActualSendActionReview: boolean; requiresReturnToExecutionOrConfirmationIfAny: boolean; nextBestActionLabel: string; payloadIntegrityBasis: string; exclusionGuardBasis: string; actorAuthorizationBasis: string; auditChainBasis: string; irreversibleTransactionBasis: string; }

export interface TransactionFieldGroup { groupKey: string; groupLabel: string; sourceMapping: string; resolved: boolean; value: string; unresolved: boolean; excluded: boolean; }
export interface ActualSendTransactionCenterCanvasStateV2 { activeSectionKey: TransactionSectionKey | null; decisionQuestion: string; transactionContext: string; sourceInputSummary: string; unresolvedOrConflictingInputs: string[]; fieldGroups: TransactionFieldGroup[]; riskSummary: string; resolutionOptions: string[]; blockedDownstreamActions: string[]; completionRuleForSection: string; }

export type TransactionPreviewMode = "locked_preview" | "transaction_candidate_preview" | "warning_preview" | "review_preview";
export interface ActualSendTransactionRightRailPreviewStateV2 { previewMode: TransactionPreviewMode; recipientPreview: { vendorId: string; contactVisible: boolean }; payloadIntegrityPreview: { lineCount: number; amountSummary: string; scopeIntact: boolean }; referenceInstructionPreview: { quoteVisible: boolean; poVisible: boolean; shipToVisible: boolean; receivingVisible: boolean }; excludedInternalOnlyPreview: InternalOnlyExcludedFlag[]; actorAuthorizationAuditPreview: { actorTraceComplete: boolean; authorizationConfirmed: boolean; auditChainIntact: boolean }; previewCautionSummary: string; provenancePreview: { candidateId: string; lane: string }[]; }

export interface ActualSendTransactionStickyDockStateV2 { primaryAction: { label: string; enabled: boolean; reason: string }; secondaryActions: { label: string; enabled: boolean; reason: string }[]; disabledActions: { label: string; reason: string }[]; blockedActionReasons: Record<string, string>; requiredResolutionBeforeProgress: string | null; workspaceCompletionLabel: string; actualSendCommitLockLabel: string; }

export interface ActualSendTransactionWorkspaceHeaderV2 { title: string; statusChip: string; entryStatusLabel: string; entryStatusReason: string; transactionScopeLabel: string; currentGateLabel: string; nextGateLabel: string; operatorMandate: string; lockInterpretation: string; actualSendCommitLockReason: string; }

export interface ActualSendTransactionWorkspaceStateV2 {
  workspaceId: string; caseId: string; handoffPackageId: string; actualSendActionSessionId: string; actualSendTransactionGateId: string;
  workspaceStatus: TransactionWorkspaceStatus; workspaceMode: TransactionWorkspaceMode;
  workspaceHeader: ActualSendTransactionWorkspaceHeaderV2; entryLockSummary: string;
  checkSectionStates: ActualSendTransactionCheckSectionStateV2[]; activeSectionKey: TransactionSectionKey | null;
  centerCanvasState: ActualSendTransactionCenterCanvasStateV2; rightRailPreview: ActualSendTransactionRightRailPreviewStateV2; stickyDock: ActualSendTransactionStickyDockStateV2;
  operatorFocusOrder: TransactionSectionKey[]; provenance: { candidateId: string; lane: string }[]; generatedAt: string;
}

const META: Record<TransactionSectionKey, { title: string; intent: string; risk: string; question: string }> = {
  recipient_transaction_block: { title: "수신자 Transaction 확인", intent: "Irreversible transaction 직전 수신자 확정", risk: "되돌릴 수 없는 오발송", question: "수신자가 irreversible transaction에 모호함 없이 확정되었습니까?" },
  payload_integrity_transaction_block: { title: "Payload Integrity Transaction 확인", intent: "최종 payload 정합성 확인", risk: "되돌릴 수 없는 주문 착오", question: "Payload가 최종 arming basis와 정합적입니까?" },
  reference_instruction_transaction_block: { title: "Reference / Instruction Transaction 확인", intent: "Reference/instruction 최종 정합성", risk: "배송/입고 착오", question: "Reference와 instruction이 최종 basis와 정합적입니까?" },
  exclusion_guard_transaction_block: { title: "Exclusion Guard Transaction 확인", intent: "Internal-only 최종 제외 확인", risk: "기밀 유출 — 되돌릴 수 없음", question: "Internal-only 문맥이 transaction candidate에서 완전 제외되었습니까?" },
  actor_authorization_audit_transaction_block: { title: "Actor / Authorization / Audit 확인", intent: "Transaction actor authorization + audit chain 확인", risk: "Actor trace / audit chain gap 시 사후 추적 불가", question: "Actor authorization과 audit chain이 irreversible transaction에 충분합니까?" },
  transaction_completion_gate_review: { title: "Transaction 완결성 확인", intent: "모든 transaction block 완결 최종 검토", risk: "미확인 상태에서 commit 시 복구 불가", question: "모든 transaction block이 완결되어 commit 준비가 되었습니까?" },
};

function buildTxnSection(key: TransactionSectionKey, rank: number, pkg: DispatchPreparationHandoffPackageV2, resolved: string[], unresolved: string[], warnings: string[]): ActualSendTransactionCheckSectionStateV2 {
  const m = META[key]; const status: TransactionSectionStatus = unresolved.length > 0 ? "blocked" : warnings.length > 0 ? "warning" : "ready";
  return { sectionKey: key, sectionTitle: m.title, sectionStatus: status, priorityRank: rank, transactionIntent: m.intent, whyThisMatters: m.risk, requiredTransactionInputs: [...resolved, ...unresolved], resolvedInputs: resolved, unresolvedOrAmbiguousInputs: unresolved, warnings, operatorActionRequired: unresolved.length > 0 ? `${m.title} 해소 필요` : warnings.length > 0 ? `${m.title} 검토` : `${m.title} 확인 가능`, canResolveInPlace: unresolved.length === 0, requiresReturnToActualSendActionReview: unresolved.length > 0, requiresReturnToExecutionOrConfirmationIfAny: false, nextBestActionLabel: unresolved.length > 0 ? `${m.title} 해소` : `${m.title} 확인`, payloadIntegrityBasis: key === "payload_integrity_transaction_block" ? "direct" : "inherited", exclusionGuardBasis: key === "exclusion_guard_transaction_block" ? "direct" : "inherited", actorAuthorizationBasis: key === "actor_authorization_audit_transaction_block" ? "direct" : "inherited", auditChainBasis: key === "actor_authorization_audit_transaction_block" ? "direct" : "inherited", irreversibleTransactionBasis: "transaction_review" };
}

function deriveSections(pkg: DispatchPreparationHandoffPackageV2): ActualSendTransactionCheckSectionStateV2[] {
  const s: ActualSendTransactionCheckSectionStateV2[] = [];
  const rR: string[] = []; const rU: string[] = []; if (pkg.createdVendorId) rR.push("vendorId"); else rU.push("vendorId"); if (pkg.vendorContactReferenceVisible) rR.push("contact"); else rU.push("contact");
  s.push(buildTxnSection("recipient_transaction_block", 1, pkg, rR, rU, []));
  const pR: string[] = []; const pU: string[] = []; const pW: string[] = []; if (pkg.createdLineItems.length > 0) pR.push("lineItems"); else pU.push("lineItems"); if (pkg.createdAmountSummary) pR.push("amount"); else pW.push("amount 누락"); if (pkg.dispatchEligibleScope) pR.push("scope"); else pU.push("scope");
  s.push(buildTxnSection("payload_integrity_transaction_block", 2, pkg, pR, pU, pW));
  const refR: string[] = []; const refU: string[] = []; const refW: string[] = []; if (pkg.quoteReferenceVisible) refR.push("quote"); else refW.push("quote 비활성"); if (pkg.poReferenceVisible) refR.push("PO"); else refW.push("PO 비활성"); if (pkg.shipToVisible) refR.push("ship-to"); else refU.push("ship-to"); if (pkg.receivingInstructionVisible) refR.push("receiving"); else refW.push("receiving 비활성");
  s.push(buildTxnSection("reference_instruction_transaction_block", 3, pkg, refR, refU, refW));
  const eR: string[] = []; const eU: string[] = []; const eW: string[] = []; if (pkg.internalOnlyExcludedFlags.length > 0) eR.push(`${pkg.internalOnlyExcludedFlags.length}건 제외`); const seedLower = (pkg.supplierFacingNoteSeed || "").toLowerCase(); if (["budget", "governance", "internal", "approval"].some(kw => seedLower.includes(kw))) eU.push("contamination risk"); if (pkg.internalOnlyExcludedFlags.length === 0 && pkg.supplierFacingNoteSeed) eW.push("exclusion flag 없이 note seed 존재");
  s.push(buildTxnSection("exclusion_guard_transaction_block", 4, pkg, eR, eU, eW));
  const aR = ["actor_trace", "authorization", "audit_chain"]; const aW: string[] = []; if (pkg.provenanceByLine.length === 0) aW.push("provenance 누락");
  s.push(buildTxnSection("actor_authorization_audit_transaction_block", 5, pkg, aR, [], aW));
  const blocked = s.filter(x => x.sectionStatus === "blocked"); const warned = s.filter(x => x.sectionStatus === "warning");
  s.push(buildTxnSection("transaction_completion_gate_review", 6, pkg, s.filter(x => x.sectionStatus === "ready" || x.sectionStatus === "reviewed").map(x => x.sectionKey), blocked.map(x => `${x.sectionTitle} blocked`), warned.map(x => `${x.sectionTitle} warning`)));
  return s;
}

function deriveStatus(gate: ActualSendTransactionGateV2, secs: ActualSendTransactionCheckSectionStateV2[]): TransactionWorkspaceStatus {
  if (gate.gateStatus !== "eligible_for_actual_send_transaction" && gate.gateStatus !== "actual_send_transaction_opened") return "locked_preview_only";
  const hasB = secs.some(x => x.sectionStatus === "blocked"); const hasW = secs.some(x => x.sectionStatus === "warning" || x.sectionStatus === "attention_required"); const allDone = secs.every(x => x.sectionStatus === "ready" || x.sectionStatus === "reviewed");
  if (allDone) return "transaction_ready_pending_commit"; if (hasB) return "transaction_review_required"; if (hasW) return "transaction_review_in_progress"; return "entry_enabled";
}
function deriveMode(s: TransactionWorkspaceStatus): TransactionWorkspaceMode { switch (s) { case "locked_preview_only": return "preview_only"; case "entry_enabled": case "transaction_review_required": return "transaction_review"; case "transaction_review_in_progress": return "irreversible_commit_check"; case "transaction_hold": return "policy_review"; case "transaction_review_pending": return "transaction_review"; case "transaction_ready_pending_commit": return "ready_pending_commit"; } }

const FOCUS: TransactionSectionKey[] = ["recipient_transaction_block", "payload_integrity_transaction_block", "reference_instruction_transaction_block", "exclusion_guard_transaction_block", "actor_authorization_audit_transaction_block", "transaction_completion_gate_review"];
function deriveFocus(secs: ActualSendTransactionCheckSectionStateV2[]): TransactionSectionKey[] { const b = FOCUS.filter(k => secs.find(x => x.sectionKey === k)?.sectionStatus === "blocked"); const w = FOCUS.filter(k => { const x = secs.find(s => s.sectionKey === k); return x && (x.sectionStatus === "warning" || x.sectionStatus === "attention_required") && !b.includes(k); }); const r = FOCUS.filter(k => !b.includes(k) && !w.includes(k)); return [...b, ...w, ...r]; }

export function buildActualSendTransactionWorkspaceStateV2(gate: ActualSendTransactionGateV2, pkg: DispatchPreparationHandoffPackageV2): ActualSendTransactionWorkspaceStateV2 {
  const secs = deriveSections(pkg); const status = deriveStatus(gate, secs); const mode = deriveMode(status); const focus = deriveFocus(secs);
  const isLocked = status === "locked_preview_only"; const isReady = status === "transaction_ready_pending_commit"; const hasB = secs.some(x => x.sectionStatus === "blocked");
  const header: ActualSendTransactionWorkspaceHeaderV2 = { title: `Actual Send Transaction — ${gate.caseId}`, statusChip: isLocked ? "Preview Only" : isReady ? "Transaction Ready — Commit 대기" : hasB ? "차단됨" : "Transaction 검토 가능", entryStatusLabel: isLocked ? "Entry Locked" : "Entry Enabled", entryStatusReason: isLocked ? gate.candidate.candidateReason : "Transaction 가능", transactionScopeLabel: gate.candidate.payloadIntegrityFinalSnapshot, currentGateLabel: "Actual Send Transaction Control", nextGateLabel: "Actual Send Commit Action (Locked — Batch 1)", operatorMandate: isLocked ? "Preview only." : hasB ? "Transaction 미확인 항목 해소 필요" : isReady ? "Transaction ready — commit 활성화를 기다리세요." : "Commit 직전 각 항목 확인", lockInterpretation: isReady ? "Transaction ready — commit은 아직 범위 밖" : isLocked ? "Gate 조건 미충족" : "Transaction 검토 가능", actualSendCommitLockReason: "Batch 1: Actual send commit, sent, dispatched 처리는 현재 범위 밖입니다" };
  const dock: ActualSendTransactionStickyDockStateV2 = { primaryAction: isLocked ? { label: "Preview Only", enabled: false, reason: "Entry locked" } : isReady ? { label: "Transaction Ready — Commit 대기", enabled: false, reason: "Commit 활성화 대기" } : hasB ? { label: "미확인 해소", enabled: true, reason: "" } : { label: "Transaction 검토 계속", enabled: true, reason: "" }, secondaryActions: [{ label: "Action Review로 복귀", enabled: true, reason: "" }, { label: "Hold 전환", enabled: true, reason: "" }, { label: "Section 확인 완료", enabled: !isLocked && !hasB, reason: hasB ? "Blocker 해소 필요" : "" }], disabledActions: [{ label: "Actual Send Commit", reason: "Batch 1 범위 밖" }, { label: "Mark Sent", reason: "Batch 1 범위 밖" }, { label: "Mark Dispatched", reason: "Batch 1 범위 밖" }, { label: "Delivery Tracking", reason: "Batch 1 범위 밖" }], blockedActionReasons: { execute_actual_send_commit: "Batch 1 금지", mark_sent: "Batch 1 금지", mark_dispatched: "Batch 1 금지", create_delivery_tracking: "Batch 1 금지" }, requiredResolutionBeforeProgress: hasB ? secs.find(x => x.sectionStatus === "blocked")?.sectionTitle ?? null : null, workspaceCompletionLabel: isReady ? "Transaction ready — commit 대기" : "Transaction 검토 진행 중", actualSendCommitLockLabel: "Actual Send Commit — Batch 1 locked" };
  const previewMode: TransactionPreviewMode = isLocked ? "locked_preview" : isReady ? "transaction_candidate_preview" : "review_preview";
  const cautions: string[] = []; if (!pkg.vendorContactReferenceVisible) cautions.push("Vendor contact 비활성"); if (!pkg.quoteReferenceVisible && !pkg.poReferenceVisible) cautions.push("Quote/PO 비활성"); if (pkg.internalOnlyExcludedFlags.length > 0) cautions.push(`${pkg.internalOnlyExcludedFlags.length}건 internal-only 제외`);
  const rail: ActualSendTransactionRightRailPreviewStateV2 = { previewMode, recipientPreview: { vendorId: pkg.createdVendorId, contactVisible: pkg.vendorContactReferenceVisible }, payloadIntegrityPreview: { lineCount: pkg.createdLineItems.length, amountSummary: pkg.createdAmountSummary, scopeIntact: !!pkg.dispatchEligibleScope }, referenceInstructionPreview: { quoteVisible: pkg.quoteReferenceVisible, poVisible: pkg.poReferenceVisible, shipToVisible: pkg.shipToVisible, receivingVisible: pkg.receivingInstructionVisible }, excludedInternalOnlyPreview: pkg.internalOnlyExcludedFlags, actorAuthorizationAuditPreview: { actorTraceComplete: pkg.provenanceByLine.length > 0, authorizationConfirmed: true, auditChainIntact: true }, previewCautionSummary: cautions.length > 0 ? cautions.join("; ") : "이슈 없음", provenancePreview: pkg.provenanceByLine.map(p => ({ candidateId: p.candidateId, lane: p.originalLane })) };
  const ak = focus[0] || null; const active = ak ? secs.find(x => x.sectionKey === ak) : null;
  const center: ActualSendTransactionCenterCanvasStateV2 = active ? { activeSectionKey: ak, decisionQuestion: META[ak!].question, transactionContext: active.transactionIntent, sourceInputSummary: `${active.resolvedInputs.length} resolved / ${active.unresolvedOrAmbiguousInputs.length} unresolved`, unresolvedOrConflictingInputs: [...active.unresolvedOrAmbiguousInputs, ...active.warnings], fieldGroups: active.requiredTransactionInputs.map(i => ({ groupKey: i, groupLabel: i, sourceMapping: "transaction", resolved: active.resolvedInputs.includes(i), value: active.resolvedInputs.includes(i) ? "resolved" : "", unresolved: active.unresolvedOrAmbiguousInputs.includes(i), excluded: false })), riskSummary: META[ak!].risk, resolutionOptions: active.canResolveInPlace ? ["현재 workspace에서 확인 가능"] : ["Action review로 복귀 필요"], blockedDownstreamActions: ["execute_actual_send_commit", "mark_sent", "mark_dispatched"], completionRuleForSection: active.unresolvedOrAmbiguousInputs.length > 0 ? "미확인 해소 후 reviewed 가능" : "즉시 reviewed 가능" } : { activeSectionKey: null, decisionQuestion: "", transactionContext: "", sourceInputSummary: "", unresolvedOrConflictingInputs: [], fieldGroups: [], riskSummary: "", resolutionOptions: [], blockedDownstreamActions: ["execute_actual_send_commit", "mark_sent", "mark_dispatched"], completionRuleForSection: "" };

  return { workspaceId: `txnws_${Date.now().toString(36)}`, caseId: gate.caseId, handoffPackageId: gate.handoffPackageId, actualSendActionSessionId: gate.actualSendActionSessionId, actualSendTransactionGateId: gate.actualSendTransactionGateId, workspaceStatus: status, workspaceMode: mode, workspaceHeader: header, entryLockSummary: isLocked ? `Entry locked: ${gate.candidate.candidateReason}` : "Entry enabled", checkSectionStates: secs, activeSectionKey: ak, centerCanvasState: center, rightRailPreview: rail, stickyDock: dock, operatorFocusOrder: focus, provenance: pkg.provenanceByLine.map(p => ({ candidateId: p.candidateId, lane: p.originalLane })), generatedAt: new Date().toISOString() };
}

export type TransactionWorkspaceEventType = "actual_send_transaction_workspace_state_computed" | "actual_send_transaction_workspace_opened_preview_only" | "actual_send_transaction_workspace_entry_enabled" | "actual_send_transaction_workspace_section_focused" | "actual_send_transaction_workspace_section_review_started" | "actual_send_transaction_workspace_marked_in_progress" | "actual_send_transaction_workspace_marked_ready_pending_commit";
export interface TransactionWorkspaceEvent { type: TransactionWorkspaceEventType; caseId: string; handoffPackageId: string; actualSendActionSessionId: string; actualSendTransactionGateId: string; workspaceId: string; sectionKeyIfAny: TransactionSectionKey | null; reason: string; actorOrSystem: string; timestamp: string; }
export function createTransactionWorkspaceEvent(type: TransactionWorkspaceEventType, ws: ActualSendTransactionWorkspaceStateV2, sectionKey: TransactionSectionKey | null, reason: string, actor: string): TransactionWorkspaceEvent { return { type, caseId: ws.caseId, handoffPackageId: ws.handoffPackageId, actualSendActionSessionId: ws.actualSendActionSessionId, actualSendTransactionGateId: ws.actualSendTransactionGateId, workspaceId: ws.workspaceId, sectionKeyIfAny: sectionKey, reason, actorOrSystem: actor, timestamp: new Date().toISOString() }; }
