-- AlterEnum: ActivityType에 주문 흐름 이벤트 타입 추가
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ORDER_FOLLOWUP_REVIEWED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ORDER_FOLLOWUP_SENT';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ORDER_STATUS_CHANGED';
